// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Packet struct {
	CmdId                uint32   `protobuf:"varint,1,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"`
	UserData             uint32   `protobuf:"varint,2,opt,name=user_data,json=userData,proto3" json:"user_data,omitempty"`
	Timestamp            uint32   `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Body                 string   `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Packet) Reset()         { *m = Packet{} }
func (m *Packet) String() string { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()    {}
func (*Packet) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{0}
}

func (m *Packet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet.Unmarshal(m, b)
}
func (m *Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet.Marshal(b, m, deterministic)
}
func (m *Packet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet.Merge(m, src)
}
func (m *Packet) XXX_Size() int {
	return xxx_messageInfo_Packet.Size(m)
}
func (m *Packet) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet.DiscardUnknown(m)
}

var xxx_messageInfo_Packet proto.InternalMessageInfo

func (m *Packet) GetCmdId() uint32 {
	if m != nil {
		return m.CmdId
	}
	return 0
}

func (m *Packet) GetUserData() uint32 {
	if m != nil {
		return m.UserData
	}
	return 0
}

func (m *Packet) GetTimestamp() uint32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Packet) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type SessionPacket struct {
	Common               *Packet  `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Sessions             []uint64 `protobuf:"varint,2,rep,packed,name=sessions,proto3" json:"sessions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionPacket) Reset()         { *m = SessionPacket{} }
func (m *SessionPacket) String() string { return proto.CompactTextString(m) }
func (*SessionPacket) ProtoMessage()    {}
func (*SessionPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{1}
}

func (m *SessionPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionPacket.Unmarshal(m, b)
}
func (m *SessionPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionPacket.Marshal(b, m, deterministic)
}
func (m *SessionPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionPacket.Merge(m, src)
}
func (m *SessionPacket) XXX_Size() int {
	return xxx_messageInfo_SessionPacket.Size(m)
}
func (m *SessionPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionPacket.DiscardUnknown(m)
}

var xxx_messageInfo_SessionPacket proto.InternalMessageInfo

func (m *SessionPacket) GetCommon() *Packet {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *SessionPacket) GetSessions() []uint64 {
	if m != nil {
		return m.Sessions
	}
	return nil
}

type SendPacketRsp struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendPacketRsp) Reset()         { *m = SendPacketRsp{} }
func (m *SendPacketRsp) String() string { return proto.CompactTextString(m) }
func (*SendPacketRsp) ProtoMessage()    {}
func (*SendPacketRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{2}
}

func (m *SendPacketRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendPacketRsp.Unmarshal(m, b)
}
func (m *SendPacketRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendPacketRsp.Marshal(b, m, deterministic)
}
func (m *SendPacketRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendPacketRsp.Merge(m, src)
}
func (m *SendPacketRsp) XXX_Size() int {
	return xxx_messageInfo_SendPacketRsp.Size(m)
}
func (m *SendPacketRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SendPacketRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SendPacketRsp proto.InternalMessageInfo

func (m *SendPacketRsp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*Packet)(nil), "protocol.packet")
	proto.RegisterType((*SessionPacket)(nil), "protocol.session_packet")
	proto.RegisterType((*SendPacketRsp)(nil), "protocol.send_packet_rsp")
}

func init() { proto.RegisterFile("core.proto", fileDescriptor_f7e43720d1edc0fe) }

var fileDescriptor_f7e43720d1edc0fe = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8e, 0x3f, 0x4f, 0x04, 0x21,
	0x10, 0xc5, 0xb3, 0x77, 0x7b, 0x64, 0x77, 0x8c, 0x7f, 0x32, 0x89, 0x86, 0xa8, 0xc5, 0x66, 0xab,
	0xb5, 0xd9, 0x42, 0xbf, 0x82, 0x8d, 0x2d, 0x85, 0x2d, 0xe1, 0x80, 0x62, 0xe3, 0xc1, 0x10, 0x86,
	0x2b, 0xfc, 0xf6, 0x46, 0x44, 0xad, 0xe0, 0xbd, 0x37, 0xf3, 0x7b, 0x03, 0x60, 0x29, 0xfb, 0x35,
	0x65, 0x2a, 0x84, 0x43, 0x7d, 0x2c, 0x9d, 0xe6, 0x08, 0x22, 0x19, 0xfb, 0xe1, 0x0b, 0xde, 0x82,
	0xb0, 0xc1, 0xe9, 0xcd, 0xc9, 0x6e, 0xea, 0x96, 0x4b, 0x75, 0xb0, 0xc1, 0xbd, 0x39, 0x7c, 0x80,
	0xf1, 0xcc, 0x3e, 0x6b, 0x67, 0x8a, 0x91, 0xbb, 0x9a, 0x0c, 0xdf, 0xc6, 0xab, 0x29, 0x06, 0x1f,
	0x61, 0x2c, 0x5b, 0xf0, 0x5c, 0x4c, 0x48, 0x72, 0x5f, 0xc3, 0x7f, 0x03, 0x11, 0xfa, 0x23, 0xb9,
	0x4f, 0xd9, 0x4f, 0xdd, 0x32, 0xaa, 0xfa, 0x9f, 0xdf, 0xe1, 0x8a, 0x3d, 0xf3, 0x46, 0x51, 0xb7,
	0xde, 0x05, 0x84, 0xa5, 0x10, 0x28, 0xd6, 0xde, 0x8b, 0xe7, 0x9b, 0xf5, 0xf7, 0xb8, 0xf5, 0x67,
	0x42, 0xb5, 0x1c, 0xef, 0x61, 0x68, 0xbb, 0x2c, 0x77, 0xd3, 0x7e, 0xe9, 0xd5, 0x9f, 0x9e, 0x9f,
	0xe0, 0x9a, 0x7d, 0x74, 0x0d, 0xaa, 0x33, 0x27, 0xbc, 0x03, 0x91, 0x3d, 0x9f, 0x4f, 0xa5, 0x82,
	0x0f, 0xaa, 0xa9, 0xa3, 0xa8, 0xfc, 0x97, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x25, 0x3a,
	0x43, 0x11, 0x01, 0x00, 0x00,
}
