// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PacketType int32

const (
	Packet_PUBLIC_BEGIN          PacketType = 0
	Packet_PRIVATE_BEGIN         PacketType = 60000
	Packet_PRIVATE_SESSION_ENTER PacketType = 60001
	Packet_PRIVATE_SESSION_LEAVE PacketType = 60002
	Packet_PRIVATE_SESSION_ROUTE PacketType = 60003
	Packet_PRIVATE_SESSION_KICK  PacketType = 60004
	Packet_PRIVATE_SESSION_PING  PacketType = 60005
	Packet_PRIVATE_SESSION_PONG  PacketType = 60006
	Packet_PRIVATE_END           PacketType = 65500
	Packet_PUBLIC_PING           PacketType = 65501
	Packet_PUBLIC_PONG           PacketType = 65502
	Packet_PUBLIC_VERCHECK       PacketType = 65534
	Packet_PUBLIC_END            PacketType = 65535
)

var PacketType_name = map[int32]string{
	0:     "PUBLIC_BEGIN",
	60000: "PRIVATE_BEGIN",
	60001: "PRIVATE_SESSION_ENTER",
	60002: "PRIVATE_SESSION_LEAVE",
	60003: "PRIVATE_SESSION_ROUTE",
	60004: "PRIVATE_SESSION_KICK",
	60005: "PRIVATE_SESSION_PING",
	60006: "PRIVATE_SESSION_PONG",
	65500: "PRIVATE_END",
	65501: "PUBLIC_PING",
	65502: "PUBLIC_PONG",
	65534: "PUBLIC_VERCHECK",
	65535: "PUBLIC_END",
}

var PacketType_value = map[string]int32{
	"PUBLIC_BEGIN":          0,
	"PRIVATE_BEGIN":         60000,
	"PRIVATE_SESSION_ENTER": 60001,
	"PRIVATE_SESSION_LEAVE": 60002,
	"PRIVATE_SESSION_ROUTE": 60003,
	"PRIVATE_SESSION_KICK":  60004,
	"PRIVATE_SESSION_PING":  60005,
	"PRIVATE_SESSION_PONG":  60006,
	"PRIVATE_END":           65500,
	"PUBLIC_PING":           65501,
	"PUBLIC_PONG":           65502,
	"PUBLIC_VERCHECK":       65534,
	"PUBLIC_END":            65535,
}

func (x PacketType) String() string {
	return proto.EnumName(PacketType_name, int32(x))
}

func (PacketType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{0, 0}
}

type Packet struct {
	CmdId                uint32   `protobuf:"varint,1,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"`
	UserData             uint32   `protobuf:"varint,2,opt,name=user_data,json=userData,proto3" json:"user_data,omitempty"`
	Timestamp            uint32   `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Body                 string   `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Packet) Reset()         { *m = Packet{} }
func (m *Packet) String() string { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()    {}
func (*Packet) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{0}
}

func (m *Packet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet.Unmarshal(m, b)
}
func (m *Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet.Marshal(b, m, deterministic)
}
func (m *Packet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet.Merge(m, src)
}
func (m *Packet) XXX_Size() int {
	return xxx_messageInfo_Packet.Size(m)
}
func (m *Packet) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet.DiscardUnknown(m)
}

var xxx_messageInfo_Packet proto.InternalMessageInfo

func (m *Packet) GetCmdId() uint32 {
	if m != nil {
		return m.CmdId
	}
	return 0
}

func (m *Packet) GetUserData() uint32 {
	if m != nil {
		return m.UserData
	}
	return 0
}

func (m *Packet) GetTimestamp() uint32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Packet) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type SessionPacket struct {
	Common               *Packet  `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Sessions             []uint64 `protobuf:"varint,2,rep,packed,name=sessions,proto3" json:"sessions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionPacket) Reset()         { *m = SessionPacket{} }
func (m *SessionPacket) String() string { return proto.CompactTextString(m) }
func (*SessionPacket) ProtoMessage()    {}
func (*SessionPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{1}
}

func (m *SessionPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionPacket.Unmarshal(m, b)
}
func (m *SessionPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionPacket.Marshal(b, m, deterministic)
}
func (m *SessionPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionPacket.Merge(m, src)
}
func (m *SessionPacket) XXX_Size() int {
	return xxx_messageInfo_SessionPacket.Size(m)
}
func (m *SessionPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionPacket.DiscardUnknown(m)
}

var xxx_messageInfo_SessionPacket proto.InternalMessageInfo

func (m *SessionPacket) GetCommon() *Packet {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *SessionPacket) GetSessions() []uint64 {
	if m != nil {
		return m.Sessions
	}
	return nil
}

type SendPacketRsp struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendPacketRsp) Reset()         { *m = SendPacketRsp{} }
func (m *SendPacketRsp) String() string { return proto.CompactTextString(m) }
func (*SendPacketRsp) ProtoMessage()    {}
func (*SendPacketRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{2}
}

func (m *SendPacketRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendPacketRsp.Unmarshal(m, b)
}
func (m *SendPacketRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendPacketRsp.Marshal(b, m, deterministic)
}
func (m *SendPacketRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendPacketRsp.Merge(m, src)
}
func (m *SendPacketRsp) XXX_Size() int {
	return xxx_messageInfo_SendPacketRsp.Size(m)
}
func (m *SendPacketRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SendPacketRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SendPacketRsp proto.InternalMessageInfo

func (m *SendPacketRsp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterEnum("protocol.PacketType", PacketType_name, PacketType_value)
	proto.RegisterType((*Packet)(nil), "protocol.packet")
	proto.RegisterType((*SessionPacket)(nil), "protocol.session_packet")
	proto.RegisterType((*SendPacketRsp)(nil), "protocol.send_packet_rsp")
}

func init() { proto.RegisterFile("core.proto", fileDescriptor_f7e43720d1edc0fe) }

var fileDescriptor_f7e43720d1edc0fe = []byte{
	// 375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x4f, 0xef, 0xd2, 0x30,
	0x18, 0xc7, 0x85, 0xee, 0xb7, 0xc0, 0xf3, 0x13, 0xa9, 0x55, 0xcc, 0x02, 0x1e, 0xc8, 0x4e, 0xf3,
	0xc2, 0x41, 0x5f, 0x01, 0x8c, 0x06, 0x17, 0xc8, 0x20, 0x05, 0x76, 0x5d, 0xc6, 0xd6, 0x03, 0x91,
	0xd1, 0x65, 0x2d, 0x07, 0x5e, 0x93, 0xef, 0xc0, 0xd7, 0xc1, 0x51, 0x8d, 0xff, 0x5f, 0x86, 0x33,
	0x94, 0xa2, 0xd1, 0xe0, 0xa9, 0x7d, 0x3e, 0x9f, 0x3e, 0xdf, 0xa4, 0xf9, 0x02, 0xa4, 0xa2, 0xe4,
	0x83, 0xa2, 0x14, 0x4a, 0x90, 0x86, 0x3e, 0x52, 0xb1, 0x73, 0xdf, 0x22, 0xb0, 0x8b, 0x24, 0x7d,
	0xc3, 0x15, 0xe9, 0x80, 0x9d, 0xe6, 0x59, 0xbc, 0xcd, 0x9c, 0x5a, 0xbf, 0xe6, 0xb5, 0xd8, 0x5d,
	0x9a, 0x67, 0x41, 0x46, 0x7a, 0xd0, 0x3c, 0x48, 0x5e, 0xc6, 0x59, 0xa2, 0x12, 0xa7, 0xae, 0x4d,
	0xe3, 0x0c, 0xc6, 0x89, 0x4a, 0xc8, 0x73, 0x68, 0xaa, 0x6d, 0xce, 0xa5, 0x4a, 0xf2, 0xc2, 0x41,
	0x5a, 0xfe, 0x01, 0x84, 0x80, 0xb5, 0x11, 0xd9, 0xd1, 0xb1, 0xfa, 0x35, 0xaf, 0xc9, 0xf4, 0xdd,
	0x7d, 0x57, 0x07, 0x4b, 0x1d, 0x0b, 0x4e, 0x30, 0x3c, 0x5c, 0xac, 0x47, 0xb3, 0xc0, 0x8f, 0x47,
	0x74, 0x12, 0x84, 0xf8, 0x01, 0x79, 0x02, 0xad, 0x05, 0x0b, 0xa2, 0xe1, 0x8a, 0x1a, 0xf4, 0xe9,
	0x84, 0x48, 0x0f, 0x3a, 0x57, 0xb8, 0xa4, 0xcb, 0x65, 0x30, 0x0f, 0x63, 0x1a, 0xae, 0x28, 0xc3,
	0x9f, 0x6f, 0xcb, 0x19, 0x1d, 0x46, 0x14, 0x7f, 0xb9, 0x2d, 0xd9, 0x7c, 0xbd, 0xa2, 0xf8, 0xeb,
	0x09, 0x91, 0x2e, 0x3c, 0xfd, 0x57, 0x4e, 0x03, 0x7f, 0x8a, 0xbf, 0xdd, 0x76, 0x8b, 0x20, 0x9c,
	0xe0, 0xef, 0xff, 0x71, 0xf3, 0x70, 0x82, 0x7f, 0x9c, 0x10, 0x79, 0x0c, 0xf7, 0x57, 0x47, 0xc3,
	0x31, 0x7e, 0x5f, 0x5d, 0xd0, 0xe5, 0x93, 0x3a, 0xe1, 0xc3, 0xdf, 0xe8, 0xbc, 0xf8, 0xb1, 0x42,
	0xa4, 0x03, 0x6d, 0x83, 0x22, 0xca, 0xfc, 0xd7, 0xd4, 0x9f, 0xe2, 0x9f, 0x15, 0x22, 0x18, 0xc0,
	0xe0, 0x73, 0x5c, 0x55, 0x21, 0x37, 0x82, 0x47, 0x92, 0x4b, 0xb9, 0x15, 0xfb, 0xd8, 0x94, 0xe6,
	0x81, 0x9d, 0x8a, 0x3c, 0x17, 0x7b, 0x5d, 0xda, 0xfd, 0x4b, 0x3c, 0xb8, 0x56, 0x3b, 0xb8, 0xbc,
	0x60, 0xc6, 0x93, 0x2e, 0x34, 0xcc, 0xae, 0x74, 0xea, 0x7d, 0xe4, 0x59, 0xec, 0xf7, 0xec, 0xbe,
	0x80, 0xb6, 0xe4, 0xfb, 0xcc, 0x84, 0xc6, 0xa5, 0x2c, 0xc8, 0x33, 0xb0, 0x4b, 0x2e, 0x0f, 0x3b,
	0xa5, 0x83, 0xef, 0x98, 0x99, 0x36, 0xb6, 0xce, 0x7f, 0xf5, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xce,
	0xf6, 0xb7, 0x75, 0x4f, 0x02, 0x00, 0x00,
}
