// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// used by cmd_id
type PacketType int32

const (
	// user type
	Packet_PUBLIC_BEGIN PacketType = 0
	// reserved type
	Packet_PRIVATE_BEGIN            PacketType = 60000
	Packet_PRIVATE_SESSION_ENTER    PacketType = 60001
	Packet_PRIVATE_SESSION_LEAVE    PacketType = 60002
	Packet_PRIVATE_SESSION_ROUTE    PacketType = 60003
	Packet_PRIVATE_SESSION_KICK     PacketType = 60004
	Packet_PRIVATE_SESSION_PING     PacketType = 60005
	Packet_PRIVATE_SESSION_PONG     PacketType = 60006
	Packet_PRIVATE_MASTER_SET       PacketType = 60011
	Packet_PRIVATE_MASTER_YOU       PacketType = 60012
	Packet_PRIVATE_MASTER_NOT       PacketType = 60013
	Packet_PRIVATE_BROADCAST_ALL    PacketType = 60021
	Packet_PRIVATE_KICK_ALL         PacketType = 60031
	Packet_PRIVATE_NOTIFY_CLIENT    PacketType = 65001
	Packet_PRIVATE_NOTIFY_VM_BIND   PacketType = 65011
	Packet_PRIVATE_NOTIFY_VM_UNBIND PacketType = 65012
	Packet_PRIVATE_END              PacketType = 65500
	Packet_PUBLIC_PING              PacketType = 65501
	Packet_PUBLIC_PONG              PacketType = 65502
	Packet_PUBLIC_SESSION_VERCHECK  PacketType = 65533
	Packet_PUBLIC_SESSION_VERREPLY  PacketType = 65534
	Packet_PUBLIC_END               PacketType = 65535
)

var PacketType_name = map[int32]string{
	0:     "PUBLIC_BEGIN",
	60000: "PRIVATE_BEGIN",
	60001: "PRIVATE_SESSION_ENTER",
	60002: "PRIVATE_SESSION_LEAVE",
	60003: "PRIVATE_SESSION_ROUTE",
	60004: "PRIVATE_SESSION_KICK",
	60005: "PRIVATE_SESSION_PING",
	60006: "PRIVATE_SESSION_PONG",
	60011: "PRIVATE_MASTER_SET",
	60012: "PRIVATE_MASTER_YOU",
	60013: "PRIVATE_MASTER_NOT",
	60021: "PRIVATE_BROADCAST_ALL",
	60031: "PRIVATE_KICK_ALL",
	65001: "PRIVATE_NOTIFY_CLIENT",
	65011: "PRIVATE_NOTIFY_VM_BIND",
	65012: "PRIVATE_NOTIFY_VM_UNBIND",
	65500: "PRIVATE_END",
	65501: "PUBLIC_PING",
	65502: "PUBLIC_PONG",
	65533: "PUBLIC_SESSION_VERCHECK",
	65534: "PUBLIC_SESSION_VERREPLY",
	65535: "PUBLIC_END",
}

var PacketType_value = map[string]int32{
	"PUBLIC_BEGIN":             0,
	"PRIVATE_BEGIN":            60000,
	"PRIVATE_SESSION_ENTER":    60001,
	"PRIVATE_SESSION_LEAVE":    60002,
	"PRIVATE_SESSION_ROUTE":    60003,
	"PRIVATE_SESSION_KICK":     60004,
	"PRIVATE_SESSION_PING":     60005,
	"PRIVATE_SESSION_PONG":     60006,
	"PRIVATE_MASTER_SET":       60011,
	"PRIVATE_MASTER_YOU":       60012,
	"PRIVATE_MASTER_NOT":       60013,
	"PRIVATE_BROADCAST_ALL":    60021,
	"PRIVATE_KICK_ALL":         60031,
	"PRIVATE_NOTIFY_CLIENT":    65001,
	"PRIVATE_NOTIFY_VM_BIND":   65011,
	"PRIVATE_NOTIFY_VM_UNBIND": 65012,
	"PRIVATE_END":              65500,
	"PUBLIC_PING":              65501,
	"PUBLIC_PONG":              65502,
	"PUBLIC_SESSION_VERCHECK":  65533,
	"PUBLIC_SESSION_VERREPLY":  65534,
	"PUBLIC_END":               65535,
}

func (x PacketType) String() string {
	return proto.EnumName(PacketType_name, int32(x))
}

func (PacketType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{0, 0}
}

type Packet struct {
	CmdId                uint32   `protobuf:"varint,1,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"`
	UserData             uint32   `protobuf:"varint,2,opt,name=user_data,json=userData,proto3" json:"user_data,omitempty"`
	Timestamp            uint32   `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Body                 string   `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Packet) Reset()         { *m = Packet{} }
func (m *Packet) String() string { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()    {}
func (*Packet) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{0}
}

func (m *Packet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet.Unmarshal(m, b)
}
func (m *Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet.Marshal(b, m, deterministic)
}
func (m *Packet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet.Merge(m, src)
}
func (m *Packet) XXX_Size() int {
	return xxx_messageInfo_Packet.Size(m)
}
func (m *Packet) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet.DiscardUnknown(m)
}

var xxx_messageInfo_Packet proto.InternalMessageInfo

func (m *Packet) GetCmdId() uint32 {
	if m != nil {
		return m.CmdId
	}
	return 0
}

func (m *Packet) GetUserData() uint32 {
	if m != nil {
		return m.UserData
	}
	return 0
}

func (m *Packet) GetTimestamp() uint32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Packet) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

// used by reserved type
type PacketReservedBody struct {
	Kv                   map[string]string `protobuf:"bytes,1,rep,name=kv,proto3" json:"kv,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PacketReservedBody) Reset()         { *m = PacketReservedBody{} }
func (m *PacketReservedBody) String() string { return proto.CompactTextString(m) }
func (*PacketReservedBody) ProtoMessage()    {}
func (*PacketReservedBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{0, 0}
}

func (m *PacketReservedBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PacketReservedBody.Unmarshal(m, b)
}
func (m *PacketReservedBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PacketReservedBody.Marshal(b, m, deterministic)
}
func (m *PacketReservedBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PacketReservedBody.Merge(m, src)
}
func (m *PacketReservedBody) XXX_Size() int {
	return xxx_messageInfo_PacketReservedBody.Size(m)
}
func (m *PacketReservedBody) XXX_DiscardUnknown() {
	xxx_messageInfo_PacketReservedBody.DiscardUnknown(m)
}

var xxx_messageInfo_PacketReservedBody proto.InternalMessageInfo

func (m *PacketReservedBody) GetKv() map[string]string {
	if m != nil {
		return m.Kv
	}
	return nil
}

type SessionPacket struct {
	Sessions             []uint64 `protobuf:"varint,1,rep,packed,name=sessions,proto3" json:"sessions,omitempty"`
	Common               *Packet  `protobuf:"bytes,2,opt,name=common,proto3" json:"common,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionPacket) Reset()         { *m = SessionPacket{} }
func (m *SessionPacket) String() string { return proto.CompactTextString(m) }
func (*SessionPacket) ProtoMessage()    {}
func (*SessionPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{1}
}

func (m *SessionPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionPacket.Unmarshal(m, b)
}
func (m *SessionPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionPacket.Marshal(b, m, deterministic)
}
func (m *SessionPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionPacket.Merge(m, src)
}
func (m *SessionPacket) XXX_Size() int {
	return xxx_messageInfo_SessionPacket.Size(m)
}
func (m *SessionPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionPacket.DiscardUnknown(m)
}

var xxx_messageInfo_SessionPacket proto.InternalMessageInfo

func (m *SessionPacket) GetSessions() []uint64 {
	if m != nil {
		return m.Sessions
	}
	return nil
}

func (m *SessionPacket) GetCommon() *Packet {
	if m != nil {
		return m.Common
	}
	return nil
}

type StreamSessionPacketRsp struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamSessionPacketRsp) Reset()         { *m = StreamSessionPacketRsp{} }
func (m *StreamSessionPacketRsp) String() string { return proto.CompactTextString(m) }
func (*StreamSessionPacketRsp) ProtoMessage()    {}
func (*StreamSessionPacketRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{2}
}

func (m *StreamSessionPacketRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamSessionPacketRsp.Unmarshal(m, b)
}
func (m *StreamSessionPacketRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamSessionPacketRsp.Marshal(b, m, deterministic)
}
func (m *StreamSessionPacketRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamSessionPacketRsp.Merge(m, src)
}
func (m *StreamSessionPacketRsp) XXX_Size() int {
	return xxx_messageInfo_StreamSessionPacketRsp.Size(m)
}
func (m *StreamSessionPacketRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamSessionPacketRsp.DiscardUnknown(m)
}

var xxx_messageInfo_StreamSessionPacketRsp proto.InternalMessageInfo

func (m *StreamSessionPacketRsp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterEnum("protocol.PacketType", PacketType_name, PacketType_value)
	proto.RegisterType((*Packet)(nil), "protocol.packet")
	proto.RegisterType((*PacketReservedBody)(nil), "protocol.packet.reserved_body")
	proto.RegisterMapType((map[string]string)(nil), "protocol.packet.reserved_body.KvEntry")
	proto.RegisterType((*SessionPacket)(nil), "protocol.session_packet")
	proto.RegisterType((*StreamSessionPacketRsp)(nil), "protocol.stream_session_packet_rsp")
}

func init() { proto.RegisterFile("core.proto", fileDescriptor_f7e43720d1edc0fe) }

var fileDescriptor_f7e43720d1edc0fe = []byte{
	// 566 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0x4f, 0x6f, 0xd3, 0x4c,
	0x10, 0x87, 0xdf, 0x64, 0x53, 0xbf, 0xcd, 0x94, 0xa2, 0x65, 0x69, 0x8b, 0x49, 0x0b, 0xaa, 0x72,
	0x40, 0x39, 0xe5, 0xd0, 0x0a, 0x84, 0xb8, 0x39, 0xce, 0x52, 0xac, 0xb8, 0x76, 0xb4, 0x76, 0x22,
	0xf5, 0xb4, 0x72, 0xed, 0x3d, 0x54, 0xa9, 0xeb, 0xc8, 0x76, 0x23, 0xe5, 0xc2, 0x67, 0xe2, 0x1b,
	0xf0, 0x25, 0x72, 0x04, 0xc4, 0x7f, 0x09, 0x01, 0x27, 0xe0, 0x54, 0x81, 0x91, 0x37, 0x36, 0x28,
	0x25, 0x3d, 0x79, 0xe7, 0x79, 0xec, 0xf1, 0x4f, 0xe3, 0x31, 0x80, 0x1f, 0xc5, 0xa2, 0x3d, 0x8e,
	0xa3, 0x34, 0x22, 0xab, 0xf2, 0xe2, 0x47, 0xa7, 0xcd, 0x67, 0x0a, 0x28, 0x63, 0xcf, 0x1f, 0x89,
	0x94, 0x6c, 0x82, 0xe2, 0x87, 0x01, 0x3f, 0x09, 0xd4, 0xca, 0x6e, 0xa5, 0xb5, 0xce, 0x56, 0xfc,
	0x30, 0x30, 0x02, 0xb2, 0x0d, 0xf5, 0xf3, 0x44, 0xc4, 0x3c, 0xf0, 0x52, 0x4f, 0xad, 0x4a, 0xb3,
	0x9a, 0x83, 0xae, 0x97, 0x7a, 0x64, 0x07, 0xea, 0xe9, 0x49, 0x28, 0x92, 0xd4, 0x0b, 0xc7, 0x2a,
	0x92, 0xf2, 0x2f, 0x20, 0x04, 0x6a, 0xc7, 0x51, 0x30, 0x55, 0x6b, 0xbb, 0x95, 0x56, 0x9d, 0xc9,
	0x73, 0xe3, 0x29, 0xac, 0xc7, 0x22, 0x11, 0xf1, 0x44, 0x04, 0x3c, 0x07, 0xe4, 0x01, 0x54, 0x47,
	0x13, 0xb5, 0xb2, 0x8b, 0x5a, 0x6b, 0x7b, 0xf7, 0xda, 0x65, 0xb0, 0xf6, 0x3c, 0x54, 0x7b, 0xe1,
	0xde, 0x76, 0x6f, 0x42, 0xcf, 0xd2, 0x78, 0xca, 0xaa, 0xa3, 0x49, 0xe3, 0x3e, 0xfc, 0x5f, 0x94,
	0x04, 0x03, 0x1a, 0x89, 0xa9, 0x8c, 0x5d, 0x67, 0xf9, 0x91, 0x6c, 0xc0, 0xca, 0xc4, 0x3b, 0x3d,
	0x17, 0x32, 0x70, 0x9d, 0xcd, 0x8b, 0x47, 0xd5, 0x87, 0x95, 0xe6, 0xf3, 0x1a, 0xd4, 0xd2, 0xe9,
	0x58, 0x10, 0x0c, 0xd7, 0xfa, 0x83, 0x8e, 0x69, 0xe8, 0xbc, 0x43, 0x0f, 0x0c, 0x0b, 0xff, 0x47,
	0x6e, 0xc2, 0x7a, 0x9f, 0x19, 0x43, 0xcd, 0xa5, 0x05, 0x7a, 0x3d, 0x43, 0x64, 0x1b, 0x36, 0x4b,
	0xe8, 0x50, 0xc7, 0x31, 0x6c, 0x8b, 0x53, 0xcb, 0xa5, 0x0c, 0xbf, 0x59, 0x2e, 0x4d, 0xaa, 0x0d,
	0x29, 0x7e, 0xbb, 0x5c, 0x32, 0x7b, 0xe0, 0x52, 0xfc, 0x6e, 0x86, 0x48, 0x03, 0x36, 0x2e, 0xcb,
	0x9e, 0xa1, 0xf7, 0xf0, 0xfb, 0xe5, 0xae, 0x6f, 0x58, 0x07, 0xf8, 0xc3, 0x15, 0xce, 0xb6, 0x0e,
	0xf0, 0xc7, 0x19, 0x22, 0x2a, 0x90, 0xd2, 0x1d, 0x6a, 0x8e, 0x4b, 0x19, 0x77, 0xa8, 0x8b, 0x3f,
	0x2f, 0x35, 0x47, 0xf6, 0x00, 0x7f, 0x59, 0x6a, 0x2c, 0xdb, 0xc5, 0x5f, 0x17, 0xe3, 0x77, 0x98,
	0xad, 0x75, 0x75, 0xcd, 0x71, 0xb9, 0x66, 0x9a, 0xf8, 0xc7, 0x0c, 0x91, 0x2d, 0xc0, 0xa5, 0xcc,
	0x63, 0x4b, 0x9e, 0x2d, 0x3e, 0x64, 0xd9, 0xae, 0xf1, 0xf8, 0x88, 0xeb, 0xa6, 0x41, 0x2d, 0x17,
	0x7f, 0xba, 0x40, 0x64, 0x07, 0xb6, 0x2e, 0xc9, 0xe1, 0x21, 0xef, 0x18, 0x56, 0x17, 0x7f, 0xbb,
	0x40, 0xe4, 0x2e, 0xa8, 0xff, 0xda, 0x81, 0x25, 0xfd, 0xf7, 0x0b, 0x44, 0x6e, 0xc0, 0x5a, 0xe9,
	0xa9, 0xd5, 0xc5, 0x2f, 0xb2, 0x39, 0x9a, 0x7f, 0x42, 0x39, 0x9f, 0x97, 0x8b, 0x28, 0x1f, 0xcb,
	0xab, 0x0c, 0x91, 0x3b, 0x70, 0xab, 0x40, 0xe5, 0xc4, 0x86, 0x94, 0xe9, 0x4f, 0xa8, 0xde, 0xc3,
	0x3f, 0xaf, 0xd2, 0x8c, 0xf6, 0xcd, 0x23, 0xfc, 0x2b, 0x43, 0x04, 0x03, 0x14, 0x3a, 0x7f, 0x6b,
	0x96, 0xa1, 0xe6, 0x10, 0xae, 0x27, 0x22, 0x49, 0x4e, 0xa2, 0x33, 0x5e, 0xfc, 0x39, 0x0d, 0x58,
	0x2d, 0x48, 0x22, 0x17, 0xb9, 0xc6, 0xfe, 0xd4, 0xa4, 0x05, 0x8a, 0x1f, 0x85, 0x61, 0x74, 0x26,
	0x57, 0x71, 0x6d, 0x0f, 0x5f, 0x5e, 0x71, 0x56, 0xf8, 0xe6, 0x3e, 0xdc, 0x4e, 0xd2, 0x58, 0x78,
	0x21, 0x5f, 0x6c, 0xcf, 0xe3, 0x64, 0x4c, 0xb6, 0x40, 0x89, 0x45, 0x72, 0x7e, 0x9a, 0xca, 0x2d,
	0x5f, 0x61, 0x45, 0x75, 0xac, 0xc8, 0x6e, 0xfb, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x97, 0xf9,
	0x65, 0x23, 0xde, 0x03, 0x00, 0x00,
}
