// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gconnd.proto

package protocol

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// master
type RegisterMasterReq struct {
	Division             string   `protobuf:"bytes,1,opt,name=division,proto3" json:"division,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterMasterReq) Reset()         { *m = RegisterMasterReq{} }
func (m *RegisterMasterReq) String() string { return proto.CompactTextString(m) }
func (*RegisterMasterReq) ProtoMessage()    {}
func (*RegisterMasterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf4e23270b453c13, []int{0}
}

func (m *RegisterMasterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterMasterReq.Unmarshal(m, b)
}
func (m *RegisterMasterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterMasterReq.Marshal(b, m, deterministic)
}
func (m *RegisterMasterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterMasterReq.Merge(m, src)
}
func (m *RegisterMasterReq) XXX_Size() int {
	return xxx_messageInfo_RegisterMasterReq.Size(m)
}
func (m *RegisterMasterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterMasterReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterMasterReq proto.InternalMessageInfo

func (m *RegisterMasterReq) GetDivision() string {
	if m != nil {
		return m.Division
	}
	return ""
}

type RegisterMasterRsp struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	MasterId             uint64   `protobuf:"varint,2,opt,name=master_id,json=masterId,proto3" json:"master_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterMasterRsp) Reset()         { *m = RegisterMasterRsp{} }
func (m *RegisterMasterRsp) String() string { return proto.CompactTextString(m) }
func (*RegisterMasterRsp) ProtoMessage()    {}
func (*RegisterMasterRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf4e23270b453c13, []int{1}
}

func (m *RegisterMasterRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterMasterRsp.Unmarshal(m, b)
}
func (m *RegisterMasterRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterMasterRsp.Marshal(b, m, deterministic)
}
func (m *RegisterMasterRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterMasterRsp.Merge(m, src)
}
func (m *RegisterMasterRsp) XXX_Size() int {
	return xxx_messageInfo_RegisterMasterRsp.Size(m)
}
func (m *RegisterMasterRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterMasterRsp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterMasterRsp proto.InternalMessageInfo

func (m *RegisterMasterRsp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *RegisterMasterRsp) GetMasterId() uint64 {
	if m != nil {
		return m.MasterId
	}
	return 0
}

// session
type SessionAliveReq struct {
	SessionId            uint64   `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionAliveReq) Reset()         { *m = SessionAliveReq{} }
func (m *SessionAliveReq) String() string { return proto.CompactTextString(m) }
func (*SessionAliveReq) ProtoMessage()    {}
func (*SessionAliveReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf4e23270b453c13, []int{2}
}

func (m *SessionAliveReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionAliveReq.Unmarshal(m, b)
}
func (m *SessionAliveReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionAliveReq.Marshal(b, m, deterministic)
}
func (m *SessionAliveReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionAliveReq.Merge(m, src)
}
func (m *SessionAliveReq) XXX_Size() int {
	return xxx_messageInfo_SessionAliveReq.Size(m)
}
func (m *SessionAliveReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionAliveReq.DiscardUnknown(m)
}

var xxx_messageInfo_SessionAliveReq proto.InternalMessageInfo

func (m *SessionAliveReq) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

type SessionAliveRsp struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionAliveRsp) Reset()         { *m = SessionAliveRsp{} }
func (m *SessionAliveRsp) String() string { return proto.CompactTextString(m) }
func (*SessionAliveRsp) ProtoMessage()    {}
func (*SessionAliveRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf4e23270b453c13, []int{3}
}

func (m *SessionAliveRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionAliveRsp.Unmarshal(m, b)
}
func (m *SessionAliveRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionAliveRsp.Marshal(b, m, deterministic)
}
func (m *SessionAliveRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionAliveRsp.Merge(m, src)
}
func (m *SessionAliveRsp) XXX_Size() int {
	return xxx_messageInfo_SessionAliveRsp.Size(m)
}
func (m *SessionAliveRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionAliveRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SessionAliveRsp proto.InternalMessageInfo

func (m *SessionAliveRsp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *SessionAliveRsp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func init() {
	proto.RegisterType((*RegisterMasterReq)(nil), "protocol.register_master_req")
	proto.RegisterType((*RegisterMasterRsp)(nil), "protocol.register_master_rsp")
	proto.RegisterType((*SessionAliveReq)(nil), "protocol.session_alive_req")
	proto.RegisterType((*SessionAliveRsp)(nil), "protocol.session_alive_rsp")
}

func init() { proto.RegisterFile("gconnd.proto", fileDescriptor_bf4e23270b453c13) }

var fileDescriptor_bf4e23270b453c13 = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x50, 0xd1, 0x4a, 0xc3, 0x40,
	0x10, 0x34, 0xd2, 0x96, 0x64, 0xd1, 0x82, 0x27, 0x94, 0x98, 0x52, 0x28, 0x79, 0xca, 0x53, 0xc0,
	0xfa, 0x05, 0x22, 0x22, 0x11, 0x85, 0x72, 0xf9, 0x80, 0x12, 0x73, 0x4b, 0x39, 0x8c, 0x77, 0xf1,
	0xee, 0x9a, 0x4f, 0xf7, 0x59, 0xba, 0xb9, 0xaa, 0x90, 0xda, 0xa7, 0x65, 0x67, 0x76, 0x66, 0x77,
	0x07, 0x2e, 0xb6, 0xb5, 0x56, 0x4a, 0xe4, 0xad, 0xd1, 0x4e, 0xb3, 0x90, 0x4a, 0xad, 0x9b, 0x04,
	0x6a, 0x6d, 0xb0, 0x47, 0xd3, 0x5b, 0xb8, 0x36, 0xb8, 0x95, 0xd6, 0xa1, 0xd9, 0x7c, 0x54, 0x54,
	0x0c, 0x7e, 0xb2, 0x04, 0x42, 0x21, 0x3b, 0x69, 0xa5, 0x56, 0x71, 0xb0, 0x0c, 0xb2, 0x88, 0xff,
	0xf4, 0xe9, 0xf3, 0x11, 0x89, 0x6d, 0xd9, 0x0c, 0x26, 0x06, 0xed, 0xae, 0x71, 0x24, 0x18, 0x73,
	0xdf, 0xb1, 0x39, 0x44, 0x7e, 0x4a, 0x8a, 0xf8, 0x7c, 0x19, 0x64, 0x23, 0x1e, 0xf6, 0x40, 0x21,
	0xd2, 0x15, 0x5c, 0x59, 0xb4, 0x7b, 0xdb, 0x4d, 0xd5, 0xc8, 0x0e, 0x69, 0xf9, 0x02, 0xe0, 0x00,
	0x4a, 0x41, 0x6e, 0x23, 0x1e, 0x79, 0xa4, 0x10, 0xe9, 0xc3, 0x40, 0x73, 0x62, 0xfb, 0x0c, 0x26,
	0xd6, 0x55, 0x6e, 0x67, 0x69, 0xf5, 0x98, 0xfb, 0x6e, 0xf5, 0x15, 0xc0, 0xe5, 0x13, 0xc5, 0x53,
	0xa2, 0xe9, 0x64, 0x8d, 0x6c, 0x0d, 0x53, 0xee, 0xdf, 0x7a, 0xa5, 0xf3, 0xd8, 0x22, 0x3f, 0x44,
	0x96, 0x1f, 0xc9, 0x28, 0x39, 0x45, 0xdb, 0x36, 0x3d, 0x63, 0x2f, 0x30, 0x2d, 0x6c, 0xd9, 0x9f,
	0x7a, 0xbf, 0xbf, 0x94, 0xcd, 0x7f, 0x25, 0x83, 0xb7, 0x93, 0xff, 0x49, 0x72, 0x7b, 0x04, 0x28,
	0x51, 0x89, 0x75, 0x55, 0xbf, 0xa3, 0x63, 0xf1, 0x70, 0xb8, 0x25, 0x26, 0xb9, 0xf9, 0xcb, 0x28,
	0xe1, 0xe1, 0xde, 0x24, 0x0b, 0xde, 0x26, 0xc4, 0xde, 0x7d, 0x07, 0x00, 0x00, 0xff, 0xff, 0x83,
	0x07, 0xfe, 0x66, 0x1d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GconndServiceClient is the client API for GconndService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GconndServiceClient interface {
	// master management
	RegisterMaster(ctx context.Context, in *RegisterMasterReq, opts ...grpc.CallOption) (*RegisterMasterRsp, error)
	// session query
	IsSessionAlive(ctx context.Context, in *SessionAliveReq, opts ...grpc.CallOption) (*SessionAliveRsp, error)
	// send packets to client(s)
	SendPacket(ctx context.Context, opts ...grpc.CallOption) (GconndService_SendPacketClient, error)
}

type gconndServiceClient struct {
	cc *grpc.ClientConn
}

func NewGconndServiceClient(cc *grpc.ClientConn) GconndServiceClient {
	return &gconndServiceClient{cc}
}

func (c *gconndServiceClient) RegisterMaster(ctx context.Context, in *RegisterMasterReq, opts ...grpc.CallOption) (*RegisterMasterRsp, error) {
	out := new(RegisterMasterRsp)
	err := c.cc.Invoke(ctx, "/protocol.GconndService/RegisterMaster", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gconndServiceClient) IsSessionAlive(ctx context.Context, in *SessionAliveReq, opts ...grpc.CallOption) (*SessionAliveRsp, error) {
	out := new(SessionAliveRsp)
	err := c.cc.Invoke(ctx, "/protocol.GconndService/IsSessionAlive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gconndServiceClient) SendPacket(ctx context.Context, opts ...grpc.CallOption) (GconndService_SendPacketClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GconndService_serviceDesc.Streams[0], "/protocol.GconndService/SendPacket", opts...)
	if err != nil {
		return nil, err
	}
	x := &gconndServiceSendPacketClient{stream}
	return x, nil
}

type GconndService_SendPacketClient interface {
	Send(*SessionPacket) error
	CloseAndRecv() (*SendPacketRsp, error)
	grpc.ClientStream
}

type gconndServiceSendPacketClient struct {
	grpc.ClientStream
}

func (x *gconndServiceSendPacketClient) Send(m *SessionPacket) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gconndServiceSendPacketClient) CloseAndRecv() (*SendPacketRsp, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SendPacketRsp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GconndServiceServer is the server API for GconndService service.
type GconndServiceServer interface {
	// master management
	RegisterMaster(context.Context, *RegisterMasterReq) (*RegisterMasterRsp, error)
	// session query
	IsSessionAlive(context.Context, *SessionAliveReq) (*SessionAliveRsp, error)
	// send packets to client(s)
	SendPacket(GconndService_SendPacketServer) error
}

// UnimplementedGconndServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGconndServiceServer struct {
}

func (*UnimplementedGconndServiceServer) RegisterMaster(ctx context.Context, req *RegisterMasterReq) (*RegisterMasterRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterMaster not implemented")
}
func (*UnimplementedGconndServiceServer) IsSessionAlive(ctx context.Context, req *SessionAliveReq) (*SessionAliveRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsSessionAlive not implemented")
}
func (*UnimplementedGconndServiceServer) SendPacket(srv GconndService_SendPacketServer) error {
	return status.Errorf(codes.Unimplemented, "method SendPacket not implemented")
}

func RegisterGconndServiceServer(s *grpc.Server, srv GconndServiceServer) {
	s.RegisterService(&_GconndService_serviceDesc, srv)
}

func _GconndService_RegisterMaster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterMasterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GconndServiceServer).RegisterMaster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.GconndService/RegisterMaster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GconndServiceServer).RegisterMaster(ctx, req.(*RegisterMasterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GconndService_IsSessionAlive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionAliveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GconndServiceServer).IsSessionAlive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.GconndService/IsSessionAlive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GconndServiceServer).IsSessionAlive(ctx, req.(*SessionAliveReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GconndService_SendPacket_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GconndServiceServer).SendPacket(&gconndServiceSendPacketServer{stream})
}

type GconndService_SendPacketServer interface {
	SendAndClose(*SendPacketRsp) error
	Recv() (*SessionPacket, error)
	grpc.ServerStream
}

type gconndServiceSendPacketServer struct {
	grpc.ServerStream
}

func (x *gconndServiceSendPacketServer) SendAndClose(m *SendPacketRsp) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gconndServiceSendPacketServer) Recv() (*SessionPacket, error) {
	m := new(SessionPacket)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _GconndService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.GconndService",
	HandlerType: (*GconndServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterMaster",
			Handler:    _GconndService_RegisterMaster_Handler,
		},
		{
			MethodName: "IsSessionAlive",
			Handler:    _GconndService_IsSessionAlive_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendPacket",
			Handler:       _GconndService_SendPacket_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "gconnd.proto",
}
