// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ghost.proto

package protocol

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GhostUserasset struct {
	Uuid                 uint64   `protobuf:"varint,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Revision             uint64   `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	Asset                string   `protobuf:"bytes,3,opt,name=asset,proto3" json:"asset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GhostUserasset) Reset()         { *m = GhostUserasset{} }
func (m *GhostUserasset) String() string { return proto.CompactTextString(m) }
func (*GhostUserasset) ProtoMessage()    {}
func (*GhostUserasset) Descriptor() ([]byte, []int) {
	return fileDescriptor_77edc9f77fb63d46, []int{0}
}

func (m *GhostUserasset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GhostUserasset.Unmarshal(m, b)
}
func (m *GhostUserasset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GhostUserasset.Marshal(b, m, deterministic)
}
func (m *GhostUserasset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GhostUserasset.Merge(m, src)
}
func (m *GhostUserasset) XXX_Size() int {
	return xxx_messageInfo_GhostUserasset.Size(m)
}
func (m *GhostUserasset) XXX_DiscardUnknown() {
	xxx_messageInfo_GhostUserasset.DiscardUnknown(m)
}

var xxx_messageInfo_GhostUserasset proto.InternalMessageInfo

func (m *GhostUserasset) GetUuid() uint64 {
	if m != nil {
		return m.Uuid
	}
	return 0
}

func (m *GhostUserasset) GetRevision() uint64 {
	if m != nil {
		return m.Revision
	}
	return 0
}

func (m *GhostUserasset) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

type RegisterVmReq struct {
	Division             string   `protobuf:"bytes,1,opt,name=division,proto3" json:"division,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterVmReq) Reset()         { *m = RegisterVmReq{} }
func (m *RegisterVmReq) String() string { return proto.CompactTextString(m) }
func (*RegisterVmReq) ProtoMessage()    {}
func (*RegisterVmReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_77edc9f77fb63d46, []int{1}
}

func (m *RegisterVmReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterVmReq.Unmarshal(m, b)
}
func (m *RegisterVmReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterVmReq.Marshal(b, m, deterministic)
}
func (m *RegisterVmReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterVmReq.Merge(m, src)
}
func (m *RegisterVmReq) XXX_Size() int {
	return xxx_messageInfo_RegisterVmReq.Size(m)
}
func (m *RegisterVmReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterVmReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterVmReq proto.InternalMessageInfo

func (m *RegisterVmReq) GetDivision() string {
	if m != nil {
		return m.Division
	}
	return ""
}

func (m *RegisterVmReq) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type RegisterVmRsp struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Vmid                 uint64   `protobuf:"varint,2,opt,name=vmid,proto3" json:"vmid,omitempty"`
	Hostid               uint64   `protobuf:"varint,3,opt,name=hostid,proto3" json:"hostid,omitempty"`
	Desc                 string   `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterVmRsp) Reset()         { *m = RegisterVmRsp{} }
func (m *RegisterVmRsp) String() string { return proto.CompactTextString(m) }
func (*RegisterVmRsp) ProtoMessage()    {}
func (*RegisterVmRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_77edc9f77fb63d46, []int{2}
}

func (m *RegisterVmRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterVmRsp.Unmarshal(m, b)
}
func (m *RegisterVmRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterVmRsp.Marshal(b, m, deterministic)
}
func (m *RegisterVmRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterVmRsp.Merge(m, src)
}
func (m *RegisterVmRsp) XXX_Size() int {
	return xxx_messageInfo_RegisterVmRsp.Size(m)
}
func (m *RegisterVmRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterVmRsp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterVmRsp proto.InternalMessageInfo

func (m *RegisterVmRsp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *RegisterVmRsp) GetVmid() uint64 {
	if m != nil {
		return m.Vmid
	}
	return 0
}

func (m *RegisterVmRsp) GetHostid() uint64 {
	if m != nil {
		return m.Hostid
	}
	return 0
}

func (m *RegisterVmRsp) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type UnregisterVmReq struct {
	Division             string   `protobuf:"bytes,1,opt,name=division,proto3" json:"division,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Vmid                 uint64   `protobuf:"varint,3,opt,name=vmid,proto3" json:"vmid,omitempty"`
	Hostid               uint64   `protobuf:"varint,4,opt,name=hostid,proto3" json:"hostid,omitempty"`
	Desc                 string   `protobuf:"bytes,5,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnregisterVmReq) Reset()         { *m = UnregisterVmReq{} }
func (m *UnregisterVmReq) String() string { return proto.CompactTextString(m) }
func (*UnregisterVmReq) ProtoMessage()    {}
func (*UnregisterVmReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_77edc9f77fb63d46, []int{3}
}

func (m *UnregisterVmReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnregisterVmReq.Unmarshal(m, b)
}
func (m *UnregisterVmReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnregisterVmReq.Marshal(b, m, deterministic)
}
func (m *UnregisterVmReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnregisterVmReq.Merge(m, src)
}
func (m *UnregisterVmReq) XXX_Size() int {
	return xxx_messageInfo_UnregisterVmReq.Size(m)
}
func (m *UnregisterVmReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UnregisterVmReq.DiscardUnknown(m)
}

var xxx_messageInfo_UnregisterVmReq proto.InternalMessageInfo

func (m *UnregisterVmReq) GetDivision() string {
	if m != nil {
		return m.Division
	}
	return ""
}

func (m *UnregisterVmReq) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *UnregisterVmReq) GetVmid() uint64 {
	if m != nil {
		return m.Vmid
	}
	return 0
}

func (m *UnregisterVmReq) GetHostid() uint64 {
	if m != nil {
		return m.Hostid
	}
	return 0
}

func (m *UnregisterVmReq) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type UnregisterVmRsp struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnregisterVmRsp) Reset()         { *m = UnregisterVmRsp{} }
func (m *UnregisterVmRsp) String() string { return proto.CompactTextString(m) }
func (*UnregisterVmRsp) ProtoMessage()    {}
func (*UnregisterVmRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_77edc9f77fb63d46, []int{4}
}

func (m *UnregisterVmRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnregisterVmRsp.Unmarshal(m, b)
}
func (m *UnregisterVmRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnregisterVmRsp.Marshal(b, m, deterministic)
}
func (m *UnregisterVmRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnregisterVmRsp.Merge(m, src)
}
func (m *UnregisterVmRsp) XXX_Size() int {
	return xxx_messageInfo_UnregisterVmRsp.Size(m)
}
func (m *UnregisterVmRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_UnregisterVmRsp.DiscardUnknown(m)
}

var xxx_messageInfo_UnregisterVmRsp proto.InternalMessageInfo

func (m *UnregisterVmRsp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *UnregisterVmRsp) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type BindSessionReq struct {
	Division             string   `protobuf:"bytes,1,opt,name=division,proto3" json:"division,omitempty"`
	Sessionid            uint64   `protobuf:"varint,2,opt,name=sessionid,proto3" json:"sessionid,omitempty"`
	Uuid                 uint64   `protobuf:"varint,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BindSessionReq) Reset()         { *m = BindSessionReq{} }
func (m *BindSessionReq) String() string { return proto.CompactTextString(m) }
func (*BindSessionReq) ProtoMessage()    {}
func (*BindSessionReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_77edc9f77fb63d46, []int{5}
}

func (m *BindSessionReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindSessionReq.Unmarshal(m, b)
}
func (m *BindSessionReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindSessionReq.Marshal(b, m, deterministic)
}
func (m *BindSessionReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindSessionReq.Merge(m, src)
}
func (m *BindSessionReq) XXX_Size() int {
	return xxx_messageInfo_BindSessionReq.Size(m)
}
func (m *BindSessionReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BindSessionReq.DiscardUnknown(m)
}

var xxx_messageInfo_BindSessionReq proto.InternalMessageInfo

func (m *BindSessionReq) GetDivision() string {
	if m != nil {
		return m.Division
	}
	return ""
}

func (m *BindSessionReq) GetSessionid() uint64 {
	if m != nil {
		return m.Sessionid
	}
	return 0
}

func (m *BindSessionReq) GetUuid() uint64 {
	if m != nil {
		return m.Uuid
	}
	return 0
}

type BindSessionRsp struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Division             string   `protobuf:"bytes,2,opt,name=division,proto3" json:"division,omitempty"`
	Sessionid            uint64   `protobuf:"varint,3,opt,name=sessionid,proto3" json:"sessionid,omitempty"`
	Uuid                 uint64   `protobuf:"varint,4,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BindSessionRsp) Reset()         { *m = BindSessionRsp{} }
func (m *BindSessionRsp) String() string { return proto.CompactTextString(m) }
func (*BindSessionRsp) ProtoMessage()    {}
func (*BindSessionRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_77edc9f77fb63d46, []int{6}
}

func (m *BindSessionRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindSessionRsp.Unmarshal(m, b)
}
func (m *BindSessionRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindSessionRsp.Marshal(b, m, deterministic)
}
func (m *BindSessionRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindSessionRsp.Merge(m, src)
}
func (m *BindSessionRsp) XXX_Size() int {
	return xxx_messageInfo_BindSessionRsp.Size(m)
}
func (m *BindSessionRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_BindSessionRsp.DiscardUnknown(m)
}

var xxx_messageInfo_BindSessionRsp proto.InternalMessageInfo

func (m *BindSessionRsp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *BindSessionRsp) GetDivision() string {
	if m != nil {
		return m.Division
	}
	return ""
}

func (m *BindSessionRsp) GetSessionid() uint64 {
	if m != nil {
		return m.Sessionid
	}
	return 0
}

func (m *BindSessionRsp) GetUuid() uint64 {
	if m != nil {
		return m.Uuid
	}
	return 0
}

type UnbindSessionReq struct {
	Division             string   `protobuf:"bytes,1,opt,name=division,proto3" json:"division,omitempty"`
	Sessionid            uint64   `protobuf:"varint,2,opt,name=sessionid,proto3" json:"sessionid,omitempty"`
	Uuid                 uint64   `protobuf:"varint,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnbindSessionReq) Reset()         { *m = UnbindSessionReq{} }
func (m *UnbindSessionReq) String() string { return proto.CompactTextString(m) }
func (*UnbindSessionReq) ProtoMessage()    {}
func (*UnbindSessionReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_77edc9f77fb63d46, []int{7}
}

func (m *UnbindSessionReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnbindSessionReq.Unmarshal(m, b)
}
func (m *UnbindSessionReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnbindSessionReq.Marshal(b, m, deterministic)
}
func (m *UnbindSessionReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnbindSessionReq.Merge(m, src)
}
func (m *UnbindSessionReq) XXX_Size() int {
	return xxx_messageInfo_UnbindSessionReq.Size(m)
}
func (m *UnbindSessionReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UnbindSessionReq.DiscardUnknown(m)
}

var xxx_messageInfo_UnbindSessionReq proto.InternalMessageInfo

func (m *UnbindSessionReq) GetDivision() string {
	if m != nil {
		return m.Division
	}
	return ""
}

func (m *UnbindSessionReq) GetSessionid() uint64 {
	if m != nil {
		return m.Sessionid
	}
	return 0
}

func (m *UnbindSessionReq) GetUuid() uint64 {
	if m != nil {
		return m.Uuid
	}
	return 0
}

type UnbindSessionRsp struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Division             string   `protobuf:"bytes,2,opt,name=division,proto3" json:"division,omitempty"`
	Sessionid            uint64   `protobuf:"varint,3,opt,name=sessionid,proto3" json:"sessionid,omitempty"`
	Uuid                 uint64   `protobuf:"varint,4,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnbindSessionRsp) Reset()         { *m = UnbindSessionRsp{} }
func (m *UnbindSessionRsp) String() string { return proto.CompactTextString(m) }
func (*UnbindSessionRsp) ProtoMessage()    {}
func (*UnbindSessionRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_77edc9f77fb63d46, []int{8}
}

func (m *UnbindSessionRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnbindSessionRsp.Unmarshal(m, b)
}
func (m *UnbindSessionRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnbindSessionRsp.Marshal(b, m, deterministic)
}
func (m *UnbindSessionRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnbindSessionRsp.Merge(m, src)
}
func (m *UnbindSessionRsp) XXX_Size() int {
	return xxx_messageInfo_UnbindSessionRsp.Size(m)
}
func (m *UnbindSessionRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_UnbindSessionRsp.DiscardUnknown(m)
}

var xxx_messageInfo_UnbindSessionRsp proto.InternalMessageInfo

func (m *UnbindSessionRsp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *UnbindSessionRsp) GetDivision() string {
	if m != nil {
		return m.Division
	}
	return ""
}

func (m *UnbindSessionRsp) GetSessionid() uint64 {
	if m != nil {
		return m.Sessionid
	}
	return 0
}

func (m *UnbindSessionRsp) GetUuid() uint64 {
	if m != nil {
		return m.Uuid
	}
	return 0
}

type LockUserassetReq struct {
	Division             string          `protobuf:"bytes,1,opt,name=division,proto3" json:"division,omitempty"`
	Sessionid            uint64          `protobuf:"varint,2,opt,name=sessionid,proto3" json:"sessionid,omitempty"`
	LockDuration         int64           `protobuf:"varint,3,opt,name=lock_duration,json=lockDuration,proto3" json:"lock_duration,omitempty"`
	Userasset            *GhostUserasset `protobuf:"bytes,4,opt,name=userasset,proto3" json:"userasset,omitempty"`
	IsRenew              bool            `protobuf:"varint,5,opt,name=is_renew,json=isRenew,proto3" json:"is_renew,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *LockUserassetReq) Reset()         { *m = LockUserassetReq{} }
func (m *LockUserassetReq) String() string { return proto.CompactTextString(m) }
func (*LockUserassetReq) ProtoMessage()    {}
func (*LockUserassetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_77edc9f77fb63d46, []int{9}
}

func (m *LockUserassetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockUserassetReq.Unmarshal(m, b)
}
func (m *LockUserassetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockUserassetReq.Marshal(b, m, deterministic)
}
func (m *LockUserassetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockUserassetReq.Merge(m, src)
}
func (m *LockUserassetReq) XXX_Size() int {
	return xxx_messageInfo_LockUserassetReq.Size(m)
}
func (m *LockUserassetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LockUserassetReq.DiscardUnknown(m)
}

var xxx_messageInfo_LockUserassetReq proto.InternalMessageInfo

func (m *LockUserassetReq) GetDivision() string {
	if m != nil {
		return m.Division
	}
	return ""
}

func (m *LockUserassetReq) GetSessionid() uint64 {
	if m != nil {
		return m.Sessionid
	}
	return 0
}

func (m *LockUserassetReq) GetLockDuration() int64 {
	if m != nil {
		return m.LockDuration
	}
	return 0
}

func (m *LockUserassetReq) GetUserasset() *GhostUserasset {
	if m != nil {
		return m.Userasset
	}
	return nil
}

func (m *LockUserassetReq) GetIsRenew() bool {
	if m != nil {
		return m.IsRenew
	}
	return false
}

type LockUserassetRsp struct {
	Result               int32           `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Newbee               int64           `protobuf:"varint,2,opt,name=newbee,proto3" json:"newbee,omitempty"`
	ExpiredTime          int64           `protobuf:"varint,3,opt,name=expired_time,json=expiredTime,proto3" json:"expired_time,omitempty"`
	Userasset            *GhostUserasset `protobuf:"bytes,4,opt,name=userasset,proto3" json:"userasset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *LockUserassetRsp) Reset()         { *m = LockUserassetRsp{} }
func (m *LockUserassetRsp) String() string { return proto.CompactTextString(m) }
func (*LockUserassetRsp) ProtoMessage()    {}
func (*LockUserassetRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_77edc9f77fb63d46, []int{10}
}

func (m *LockUserassetRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockUserassetRsp.Unmarshal(m, b)
}
func (m *LockUserassetRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockUserassetRsp.Marshal(b, m, deterministic)
}
func (m *LockUserassetRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockUserassetRsp.Merge(m, src)
}
func (m *LockUserassetRsp) XXX_Size() int {
	return xxx_messageInfo_LockUserassetRsp.Size(m)
}
func (m *LockUserassetRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_LockUserassetRsp.DiscardUnknown(m)
}

var xxx_messageInfo_LockUserassetRsp proto.InternalMessageInfo

func (m *LockUserassetRsp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *LockUserassetRsp) GetNewbee() int64 {
	if m != nil {
		return m.Newbee
	}
	return 0
}

func (m *LockUserassetRsp) GetExpiredTime() int64 {
	if m != nil {
		return m.ExpiredTime
	}
	return 0
}

func (m *LockUserassetRsp) GetUserasset() *GhostUserasset {
	if m != nil {
		return m.Userasset
	}
	return nil
}

type UnlockUserassetReq struct {
	Sessionid            uint64          `protobuf:"varint,1,opt,name=sessionid,proto3" json:"sessionid,omitempty"`
	Userasset            *GhostUserasset `protobuf:"bytes,2,opt,name=userasset,proto3" json:"userasset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UnlockUserassetReq) Reset()         { *m = UnlockUserassetReq{} }
func (m *UnlockUserassetReq) String() string { return proto.CompactTextString(m) }
func (*UnlockUserassetReq) ProtoMessage()    {}
func (*UnlockUserassetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_77edc9f77fb63d46, []int{11}
}

func (m *UnlockUserassetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnlockUserassetReq.Unmarshal(m, b)
}
func (m *UnlockUserassetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnlockUserassetReq.Marshal(b, m, deterministic)
}
func (m *UnlockUserassetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnlockUserassetReq.Merge(m, src)
}
func (m *UnlockUserassetReq) XXX_Size() int {
	return xxx_messageInfo_UnlockUserassetReq.Size(m)
}
func (m *UnlockUserassetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UnlockUserassetReq.DiscardUnknown(m)
}

var xxx_messageInfo_UnlockUserassetReq proto.InternalMessageInfo

func (m *UnlockUserassetReq) GetSessionid() uint64 {
	if m != nil {
		return m.Sessionid
	}
	return 0
}

func (m *UnlockUserassetReq) GetUserasset() *GhostUserasset {
	if m != nil {
		return m.Userasset
	}
	return nil
}

type UnlockUserassetRsp struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnlockUserassetRsp) Reset()         { *m = UnlockUserassetRsp{} }
func (m *UnlockUserassetRsp) String() string { return proto.CompactTextString(m) }
func (*UnlockUserassetRsp) ProtoMessage()    {}
func (*UnlockUserassetRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_77edc9f77fb63d46, []int{12}
}

func (m *UnlockUserassetRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnlockUserassetRsp.Unmarshal(m, b)
}
func (m *UnlockUserassetRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnlockUserassetRsp.Marshal(b, m, deterministic)
}
func (m *UnlockUserassetRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnlockUserassetRsp.Merge(m, src)
}
func (m *UnlockUserassetRsp) XXX_Size() int {
	return xxx_messageInfo_UnlockUserassetRsp.Size(m)
}
func (m *UnlockUserassetRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_UnlockUserassetRsp.DiscardUnknown(m)
}

var xxx_messageInfo_UnlockUserassetRsp proto.InternalMessageInfo

func (m *UnlockUserassetRsp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type DebugReq struct {
	Division             string   `protobuf:"bytes,1,opt,name=division,proto3" json:"division,omitempty"`
	Cmdop                string   `protobuf:"bytes,2,opt,name=cmdop,proto3" json:"cmdop,omitempty"`
	Cmdparam             string   `protobuf:"bytes,3,opt,name=cmdparam,proto3" json:"cmdparam,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DebugReq) Reset()         { *m = DebugReq{} }
func (m *DebugReq) String() string { return proto.CompactTextString(m) }
func (*DebugReq) ProtoMessage()    {}
func (*DebugReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_77edc9f77fb63d46, []int{13}
}

func (m *DebugReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DebugReq.Unmarshal(m, b)
}
func (m *DebugReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DebugReq.Marshal(b, m, deterministic)
}
func (m *DebugReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DebugReq.Merge(m, src)
}
func (m *DebugReq) XXX_Size() int {
	return xxx_messageInfo_DebugReq.Size(m)
}
func (m *DebugReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DebugReq.DiscardUnknown(m)
}

var xxx_messageInfo_DebugReq proto.InternalMessageInfo

func (m *DebugReq) GetDivision() string {
	if m != nil {
		return m.Division
	}
	return ""
}

func (m *DebugReq) GetCmdop() string {
	if m != nil {
		return m.Cmdop
	}
	return ""
}

func (m *DebugReq) GetCmdparam() string {
	if m != nil {
		return m.Cmdparam
	}
	return ""
}

type DebugRsp struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DebugRsp) Reset()         { *m = DebugRsp{} }
func (m *DebugRsp) String() string { return proto.CompactTextString(m) }
func (*DebugRsp) ProtoMessage()    {}
func (*DebugRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_77edc9f77fb63d46, []int{14}
}

func (m *DebugRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DebugRsp.Unmarshal(m, b)
}
func (m *DebugRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DebugRsp.Marshal(b, m, deterministic)
}
func (m *DebugRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DebugRsp.Merge(m, src)
}
func (m *DebugRsp) XXX_Size() int {
	return xxx_messageInfo_DebugRsp.Size(m)
}
func (m *DebugRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DebugRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DebugRsp proto.InternalMessageInfo

func (m *DebugRsp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *DebugRsp) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type NotifyStatusReq struct {
	Status               uint32   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyStatusReq) Reset()         { *m = NotifyStatusReq{} }
func (m *NotifyStatusReq) String() string { return proto.CompactTextString(m) }
func (*NotifyStatusReq) ProtoMessage()    {}
func (*NotifyStatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_77edc9f77fb63d46, []int{15}
}

func (m *NotifyStatusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyStatusReq.Unmarshal(m, b)
}
func (m *NotifyStatusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyStatusReq.Marshal(b, m, deterministic)
}
func (m *NotifyStatusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyStatusReq.Merge(m, src)
}
func (m *NotifyStatusReq) XXX_Size() int {
	return xxx_messageInfo_NotifyStatusReq.Size(m)
}
func (m *NotifyStatusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyStatusReq.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyStatusReq proto.InternalMessageInfo

func (m *NotifyStatusReq) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type NotifyStatusRsp struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyStatusRsp) Reset()         { *m = NotifyStatusRsp{} }
func (m *NotifyStatusRsp) String() string { return proto.CompactTextString(m) }
func (*NotifyStatusRsp) ProtoMessage()    {}
func (*NotifyStatusRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_77edc9f77fb63d46, []int{16}
}

func (m *NotifyStatusRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyStatusRsp.Unmarshal(m, b)
}
func (m *NotifyStatusRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyStatusRsp.Marshal(b, m, deterministic)
}
func (m *NotifyStatusRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyStatusRsp.Merge(m, src)
}
func (m *NotifyStatusRsp) XXX_Size() int {
	return xxx_messageInfo_NotifyStatusRsp.Size(m)
}
func (m *NotifyStatusRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyStatusRsp.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyStatusRsp proto.InternalMessageInfo

func (m *NotifyStatusRsp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *NotifyStatusRsp) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func init() {
	proto.RegisterType((*GhostUserasset)(nil), "protocol.ghost_userasset")
	proto.RegisterType((*RegisterVmReq)(nil), "protocol.register_vm_req")
	proto.RegisterType((*RegisterVmRsp)(nil), "protocol.register_vm_rsp")
	proto.RegisterType((*UnregisterVmReq)(nil), "protocol.unregister_vm_req")
	proto.RegisterType((*UnregisterVmRsp)(nil), "protocol.unregister_vm_rsp")
	proto.RegisterType((*BindSessionReq)(nil), "protocol.bind_session_req")
	proto.RegisterType((*BindSessionRsp)(nil), "protocol.bind_session_rsp")
	proto.RegisterType((*UnbindSessionReq)(nil), "protocol.unbind_session_req")
	proto.RegisterType((*UnbindSessionRsp)(nil), "protocol.unbind_session_rsp")
	proto.RegisterType((*LockUserassetReq)(nil), "protocol.lock_userasset_req")
	proto.RegisterType((*LockUserassetRsp)(nil), "protocol.lock_userasset_rsp")
	proto.RegisterType((*UnlockUserassetReq)(nil), "protocol.unlock_userasset_req")
	proto.RegisterType((*UnlockUserassetRsp)(nil), "protocol.unlock_userasset_rsp")
	proto.RegisterType((*DebugReq)(nil), "protocol.debug_req")
	proto.RegisterType((*DebugRsp)(nil), "protocol.debug_rsp")
	proto.RegisterType((*NotifyStatusReq)(nil), "protocol.notify_status_req")
	proto.RegisterType((*NotifyStatusRsp)(nil), "protocol.notify_status_rsp")
}

func init() { proto.RegisterFile("ghost.proto", fileDescriptor_77edc9f77fb63d46) }

var fileDescriptor_77edc9f77fb63d46 = []byte{
	// 731 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xae, 0x13, 0x27, 0x4d, 0x26, 0xa9, 0x4a, 0x97, 0xaa, 0x4a, 0x4d, 0x85, 0x8a, 0x7b, 0xa9,
	0x84, 0x14, 0xa1, 0xf6, 0xd0, 0x23, 0x02, 0x55, 0xaa, 0xa8, 0x08, 0x42, 0x0e, 0x29, 0xe2, 0x64,
	0x12, 0x7b, 0x69, 0x57, 0x8d, 0xed, 0x74, 0xd7, 0x4e, 0x0b, 0x6f, 0xc0, 0x91, 0x37, 0xe0, 0x6d,
	0x78, 0x1a, 0xde, 0x01, 0xed, 0x78, 0x63, 0xbb, 0x76, 0xec, 0xaa, 0xfc, 0x9d, 0xe2, 0xd9, 0x99,
	0xfd, 0xbe, 0x6f, 0x26, 0x9f, 0x27, 0x81, 0xce, 0xf9, 0x45, 0x20, 0xc2, 0xfe, 0x8c, 0x07, 0x61,
	0x40, 0x5a, 0xf8, 0xe1, 0x04, 0x53, 0xa3, 0x3b, 0x1b, 0x3b, 0x97, 0x54, 0x9d, 0x9b, 0xef, 0x61,
	0x1d, 0xcb, 0xec, 0x48, 0x50, 0x3e, 0x16, 0x82, 0x86, 0x84, 0x80, 0x1e, 0x45, 0xcc, 0xed, 0x69,
	0xbb, 0xda, 0xbe, 0x6e, 0xe1, 0x33, 0x31, 0xa0, 0xc5, 0xe9, 0x9c, 0x09, 0x16, 0xf8, 0xbd, 0x1a,
	0x9e, 0x27, 0x31, 0xd9, 0x84, 0x06, 0x5e, 0xec, 0xd5, 0x77, 0xb5, 0xfd, 0xb6, 0x15, 0x07, 0xe6,
	0x09, 0xac, 0x73, 0x7a, 0xce, 0x44, 0x48, 0xb9, 0x3d, 0xf7, 0x6c, 0x4e, 0xaf, 0x24, 0x88, 0xcb,
	0x14, 0x88, 0x86, 0xb5, 0x49, 0x4c, 0x7a, 0xb0, 0x3a, 0xa7, 0x3c, 0xc1, 0x6f, 0x5b, 0x8b, 0xd0,
	0x64, 0x39, 0x20, 0x31, 0x23, 0x5b, 0xd0, 0xe4, 0x54, 0x44, 0xd3, 0x10, 0x61, 0x1a, 0x96, 0x8a,
	0xa4, 0xf2, 0xb9, 0xc7, 0x5c, 0xa5, 0x10, 0x9f, 0x65, 0xad, 0xec, 0x8f, 0xb9, 0x28, 0x4f, 0xb7,
	0x54, 0x24, 0x6b, 0x5d, 0x2a, 0x9c, 0x9e, 0x8e, 0x6c, 0xf8, 0x6c, 0x7e, 0xd5, 0x60, 0x23, 0xf2,
	0xff, 0x8a, 0xec, 0x44, 0x4b, 0x7d, 0xa9, 0x16, 0x7d, 0xa9, 0x96, 0x46, 0x46, 0xcb, 0xf3, 0x82,
	0x94, 0xea, 0xc6, 0x11, 0xa0, 0x96, 0x01, 0xf8, 0x08, 0x0f, 0x26, 0xcc, 0x77, 0x6d, 0x41, 0x85,
	0x14, 0x74, 0x67, 0x2b, 0x3b, 0xd0, 0x56, 0xa5, 0xc9, 0x04, 0xd3, 0x83, 0xc4, 0x14, 0xf5, 0xd4,
	0x14, 0xe6, 0x4d, 0x9e, 0xa1, 0x42, 0x61, 0x96, 0xb9, 0x56, 0xc5, 0x5c, 0x2f, 0x63, 0xd6, 0x33,
	0xcc, 0x13, 0x20, 0x91, 0xff, 0x8f, 0xbb, 0xfb, 0x52, 0xe4, 0xf8, 0x6f, 0xfd, 0xfd, 0xd0, 0x80,
	0x4c, 0x03, 0xe7, 0x32, 0x7d, 0x2b, 0xff, 0xb0, 0xc1, 0x3d, 0x58, 0x43, 0x3c, 0x37, 0xe2, 0xe3,
	0x50, 0x5e, 0x97, 0x32, 0xea, 0x56, 0x57, 0x1e, 0x1e, 0xab, 0x33, 0x72, 0x04, 0xed, 0x84, 0x0f,
	0xe5, 0x74, 0x0e, 0xb6, 0xfb, 0x8b, 0xbd, 0xd1, 0xcf, 0xad, 0x09, 0x2b, 0xad, 0x25, 0xdb, 0xd0,
	0x62, 0xc2, 0xe6, 0xd4, 0xa7, 0xd7, 0xe8, 0xe1, 0x96, 0xb5, 0xca, 0x84, 0x25, 0x43, 0xf3, 0xfb,
	0x92, 0x4e, 0x2a, 0xc6, 0xb8, 0x05, 0x4d, 0x9f, 0x5e, 0x4f, 0x28, 0xc5, 0x16, 0xea, 0x96, 0x8a,
	0xc8, 0x13, 0xe8, 0xd2, 0x9b, 0x19, 0xe3, 0xd4, 0xb5, 0x43, 0xe6, 0x51, 0x25, 0xbf, 0xa3, 0xce,
	0xde, 0x31, 0x8f, 0xfe, 0xb6, 0x7a, 0xd3, 0x83, 0xcd, 0xc8, 0x5f, 0x32, 0xed, 0x5b, 0x13, 0xd5,
	0xf2, 0x13, 0xbd, 0x45, 0x57, 0xbb, 0x07, 0x5d, 0x7f, 0x19, 0x5d, 0xf9, 0x48, 0xcc, 0x0f, 0xd0,
	0x76, 0xe9, 0x24, 0x3a, 0xbf, 0xd3, 0x01, 0x9b, 0xd0, 0x70, 0x3c, 0x37, 0x98, 0x29, 0xff, 0xc5,
	0x81, 0xbc, 0xe1, 0x78, 0xee, 0x6c, 0xcc, 0xc7, 0x9e, 0x5a, 0xd0, 0x49, 0x6c, 0x1e, 0x25, 0xd0,
	0xf7, 0xdc, 0x2d, 0x4f, 0x61, 0xc3, 0x0f, 0x42, 0xf6, 0xe9, 0xb3, 0x2d, 0xc2, 0x71, 0x18, 0x09,
	0xd4, 0xb6, 0x05, 0xcd, 0x38, 0x42, 0x80, 0x35, 0x4b, 0x45, 0x72, 0x93, 0xe5, 0x8a, 0xef, 0xc7,
	0x76, 0xf0, 0x4d, 0x87, 0xee, 0x89, 0x1c, 0xe8, 0x90, 0xf2, 0x39, 0x73, 0x28, 0x39, 0x06, 0xb0,
	0xd4, 0x66, 0x3c, 0x1b, 0x90, 0xcc, 0xd8, 0x73, 0xab, 0xdb, 0x28, 0x4b, 0x89, 0x99, 0xb9, 0x42,
	0x4e, 0xa1, 0x3b, 0x4a, 0x36, 0xec, 0xd9, 0x80, 0x3c, 0x4a, 0x8b, 0x0b, 0x3f, 0x02, 0x46, 0x79,
	0x12, 0xb1, 0x4e, 0xa0, 0xf3, 0x92, 0xf9, 0xee, 0x30, 0xb6, 0x07, 0x31, 0xd2, 0xea, 0xfc, 0x96,
	0x32, 0x4a, 0x73, 0x08, 0x34, 0x80, 0xb5, 0x11, 0x6e, 0x9d, 0x05, 0xd4, 0x4e, 0x96, 0xb8, 0x00,
	0x56, 0x91, 0x5d, 0xc0, 0xbd, 0x0e, 0x9c, 0xcb, 0x91, 0xa0, 0xfc, 0x05, 0xbe, 0xaa, 0x99, 0x0b,
	0x45, 0xcb, 0x1b, 0x15, 0x59, 0x84, 0x1b, 0xc2, 0xfa, 0x08, 0xbd, 0x9b, 0x02, 0x3e, 0xce, 0x2a,
	0x58, 0x02, 0x59, 0x99, 0x47, 0xd0, 0x43, 0x68, 0x1c, 0x4b, 0x17, 0x92, 0x87, 0x69, 0x69, 0xe2,
	0x78, 0xa3, 0x78, 0x28, 0x2f, 0x1d, 0xfc, 0xd4, 0xa0, 0x7d, 0x36, 0x58, 0x18, 0xe2, 0x14, 0xba,
	0x6f, 0xd0, 0x62, 0x43, 0x74, 0x58, 0xf6, 0xab, 0x2c, 0xf8, 0xd4, 0x28, 0x4f, 0xa2, 0x9c, 0x57,
	0xa0, 0xbf, 0x8d, 0xc4, 0x05, 0xe9, 0xa5, 0x65, 0x8b, 0x99, 0xc6, 0xff, 0x9c, 0x8c, 0xbd, 0x4c,
	0x26, 0xe4, 0x74, 0xec, 0xd9, 0xb7, 0x0b, 0x62, 0xa0, 0x7d, 0x2d, 0x86, 0x9a, 0x4e, 0xc9, 0xdd,
	0x17, 0xe8, 0x95, 0x51, 0xca, 0x67, 0xae, 0x3c, 0xd3, 0x26, 0x4d, 0x4c, 0x1e, 0xfe, 0x0a, 0x00,
	0x00, 0xff, 0xff, 0xa8, 0xe9, 0x8e, 0xb0, 0xd5, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GhostServiceClient is the client API for GhostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GhostServiceClient interface {
	// vm management
	RegisterVM(ctx context.Context, in *RegisterVmReq, opts ...grpc.CallOption) (*RegisterVmRsp, error)
	UnregisterVM(ctx context.Context, in *UnregisterVmReq, opts ...grpc.CallOption) (*UnregisterVmRsp, error)
	// session bind & unbind with uuid(user unique id)
	BindSession(ctx context.Context, in *BindSessionReq, opts ...grpc.CallOption) (*BindSessionRsp, error)
	UnbindSession(ctx context.Context, in *UnbindSessionReq, opts ...grpc.CallOption) (*UnbindSessionRsp, error)
	// user asset lock & unlock
	LockUserAsset(ctx context.Context, in *LockUserassetReq, opts ...grpc.CallOption) (*LockUserassetRsp, error)
	UnlockUserAsset(ctx context.Context, in *UnlockUserassetReq, opts ...grpc.CallOption) (*UnlockUserassetRsp, error)
	// debug
	Debug(ctx context.Context, in *DebugReq, opts ...grpc.CallOption) (*DebugRsp, error)
}

type ghostServiceClient struct {
	cc *grpc.ClientConn
}

func NewGhostServiceClient(cc *grpc.ClientConn) GhostServiceClient {
	return &ghostServiceClient{cc}
}

func (c *ghostServiceClient) RegisterVM(ctx context.Context, in *RegisterVmReq, opts ...grpc.CallOption) (*RegisterVmRsp, error) {
	out := new(RegisterVmRsp)
	err := c.cc.Invoke(ctx, "/protocol.GhostService/RegisterVM", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ghostServiceClient) UnregisterVM(ctx context.Context, in *UnregisterVmReq, opts ...grpc.CallOption) (*UnregisterVmRsp, error) {
	out := new(UnregisterVmRsp)
	err := c.cc.Invoke(ctx, "/protocol.GhostService/UnregisterVM", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ghostServiceClient) BindSession(ctx context.Context, in *BindSessionReq, opts ...grpc.CallOption) (*BindSessionRsp, error) {
	out := new(BindSessionRsp)
	err := c.cc.Invoke(ctx, "/protocol.GhostService/BindSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ghostServiceClient) UnbindSession(ctx context.Context, in *UnbindSessionReq, opts ...grpc.CallOption) (*UnbindSessionRsp, error) {
	out := new(UnbindSessionRsp)
	err := c.cc.Invoke(ctx, "/protocol.GhostService/UnbindSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ghostServiceClient) LockUserAsset(ctx context.Context, in *LockUserassetReq, opts ...grpc.CallOption) (*LockUserassetRsp, error) {
	out := new(LockUserassetRsp)
	err := c.cc.Invoke(ctx, "/protocol.GhostService/LockUserAsset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ghostServiceClient) UnlockUserAsset(ctx context.Context, in *UnlockUserassetReq, opts ...grpc.CallOption) (*UnlockUserassetRsp, error) {
	out := new(UnlockUserassetRsp)
	err := c.cc.Invoke(ctx, "/protocol.GhostService/UnlockUserAsset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ghostServiceClient) Debug(ctx context.Context, in *DebugReq, opts ...grpc.CallOption) (*DebugRsp, error) {
	out := new(DebugRsp)
	err := c.cc.Invoke(ctx, "/protocol.GhostService/Debug", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GhostServiceServer is the server API for GhostService service.
type GhostServiceServer interface {
	// vm management
	RegisterVM(context.Context, *RegisterVmReq) (*RegisterVmRsp, error)
	UnregisterVM(context.Context, *UnregisterVmReq) (*UnregisterVmRsp, error)
	// session bind & unbind with uuid(user unique id)
	BindSession(context.Context, *BindSessionReq) (*BindSessionRsp, error)
	UnbindSession(context.Context, *UnbindSessionReq) (*UnbindSessionRsp, error)
	// user asset lock & unlock
	LockUserAsset(context.Context, *LockUserassetReq) (*LockUserassetRsp, error)
	UnlockUserAsset(context.Context, *UnlockUserassetReq) (*UnlockUserassetRsp, error)
	// debug
	Debug(context.Context, *DebugReq) (*DebugRsp, error)
}

// UnimplementedGhostServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGhostServiceServer struct {
}

func (*UnimplementedGhostServiceServer) RegisterVM(ctx context.Context, req *RegisterVmReq) (*RegisterVmRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterVM not implemented")
}
func (*UnimplementedGhostServiceServer) UnregisterVM(ctx context.Context, req *UnregisterVmReq) (*UnregisterVmRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterVM not implemented")
}
func (*UnimplementedGhostServiceServer) BindSession(ctx context.Context, req *BindSessionReq) (*BindSessionRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BindSession not implemented")
}
func (*UnimplementedGhostServiceServer) UnbindSession(ctx context.Context, req *UnbindSessionReq) (*UnbindSessionRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnbindSession not implemented")
}
func (*UnimplementedGhostServiceServer) LockUserAsset(ctx context.Context, req *LockUserassetReq) (*LockUserassetRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LockUserAsset not implemented")
}
func (*UnimplementedGhostServiceServer) UnlockUserAsset(ctx context.Context, req *UnlockUserassetReq) (*UnlockUserassetRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnlockUserAsset not implemented")
}
func (*UnimplementedGhostServiceServer) Debug(ctx context.Context, req *DebugReq) (*DebugRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Debug not implemented")
}

func RegisterGhostServiceServer(s *grpc.Server, srv GhostServiceServer) {
	s.RegisterService(&_GhostService_serviceDesc, srv)
}

func _GhostService_RegisterVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterVmReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GhostServiceServer).RegisterVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.GhostService/RegisterVM",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GhostServiceServer).RegisterVM(ctx, req.(*RegisterVmReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GhostService_UnregisterVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterVmReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GhostServiceServer).UnregisterVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.GhostService/UnregisterVM",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GhostServiceServer).UnregisterVM(ctx, req.(*UnregisterVmReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GhostService_BindSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindSessionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GhostServiceServer).BindSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.GhostService/BindSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GhostServiceServer).BindSession(ctx, req.(*BindSessionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GhostService_UnbindSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnbindSessionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GhostServiceServer).UnbindSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.GhostService/UnbindSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GhostServiceServer).UnbindSession(ctx, req.(*UnbindSessionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GhostService_LockUserAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockUserassetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GhostServiceServer).LockUserAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.GhostService/LockUserAsset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GhostServiceServer).LockUserAsset(ctx, req.(*LockUserassetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GhostService_UnlockUserAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockUserassetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GhostServiceServer).UnlockUserAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.GhostService/UnlockUserAsset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GhostServiceServer).UnlockUserAsset(ctx, req.(*UnlockUserassetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GhostService_Debug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DebugReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GhostServiceServer).Debug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.GhostService/Debug",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GhostServiceServer).Debug(ctx, req.(*DebugReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _GhostService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.GhostService",
	HandlerType: (*GhostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterVM",
			Handler:    _GhostService_RegisterVM_Handler,
		},
		{
			MethodName: "UnregisterVM",
			Handler:    _GhostService_UnregisterVM_Handler,
		},
		{
			MethodName: "BindSession",
			Handler:    _GhostService_BindSession_Handler,
		},
		{
			MethodName: "UnbindSession",
			Handler:    _GhostService_UnbindSession_Handler,
		},
		{
			MethodName: "LockUserAsset",
			Handler:    _GhostService_LockUserAsset_Handler,
		},
		{
			MethodName: "UnlockUserAsset",
			Handler:    _GhostService_UnlockUserAsset_Handler,
		},
		{
			MethodName: "Debug",
			Handler:    _GhostService_Debug_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ghost.proto",
}

// VMServiceClient is the client API for VMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VMServiceClient interface {
	NotifyStatus(ctx context.Context, in *NotifyStatusReq, opts ...grpc.CallOption) (*NotifyStatusRsp, error)
	Push(ctx context.Context, opts ...grpc.CallOption) (VMService_PushClient, error)
	Pull(ctx context.Context, in *StreamSessionPacketReq, opts ...grpc.CallOption) (VMService_PullClient, error)
}

type vMServiceClient struct {
	cc *grpc.ClientConn
}

func NewVMServiceClient(cc *grpc.ClientConn) VMServiceClient {
	return &vMServiceClient{cc}
}

func (c *vMServiceClient) NotifyStatus(ctx context.Context, in *NotifyStatusReq, opts ...grpc.CallOption) (*NotifyStatusRsp, error) {
	out := new(NotifyStatusRsp)
	err := c.cc.Invoke(ctx, "/protocol.VMService/NotifyStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServiceClient) Push(ctx context.Context, opts ...grpc.CallOption) (VMService_PushClient, error) {
	stream, err := c.cc.NewStream(ctx, &_VMService_serviceDesc.Streams[0], "/protocol.VMService/Push", opts...)
	if err != nil {
		return nil, err
	}
	x := &vMServicePushClient{stream}
	return x, nil
}

type VMService_PushClient interface {
	Send(*SessionPacket) error
	CloseAndRecv() (*StreamSessionPacketRsp, error)
	grpc.ClientStream
}

type vMServicePushClient struct {
	grpc.ClientStream
}

func (x *vMServicePushClient) Send(m *SessionPacket) error {
	return x.ClientStream.SendMsg(m)
}

func (x *vMServicePushClient) CloseAndRecv() (*StreamSessionPacketRsp, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(StreamSessionPacketRsp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *vMServiceClient) Pull(ctx context.Context, in *StreamSessionPacketReq, opts ...grpc.CallOption) (VMService_PullClient, error) {
	stream, err := c.cc.NewStream(ctx, &_VMService_serviceDesc.Streams[1], "/protocol.VMService/Pull", opts...)
	if err != nil {
		return nil, err
	}
	x := &vMServicePullClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type VMService_PullClient interface {
	Recv() (*SessionPacket, error)
	grpc.ClientStream
}

type vMServicePullClient struct {
	grpc.ClientStream
}

func (x *vMServicePullClient) Recv() (*SessionPacket, error) {
	m := new(SessionPacket)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// VMServiceServer is the server API for VMService service.
type VMServiceServer interface {
	NotifyStatus(context.Context, *NotifyStatusReq) (*NotifyStatusRsp, error)
	Push(VMService_PushServer) error
	Pull(*StreamSessionPacketReq, VMService_PullServer) error
}

// UnimplementedVMServiceServer can be embedded to have forward compatible implementations.
type UnimplementedVMServiceServer struct {
}

func (*UnimplementedVMServiceServer) NotifyStatus(ctx context.Context, req *NotifyStatusReq) (*NotifyStatusRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyStatus not implemented")
}
func (*UnimplementedVMServiceServer) Push(srv VMService_PushServer) error {
	return status.Errorf(codes.Unimplemented, "method Push not implemented")
}
func (*UnimplementedVMServiceServer) Pull(req *StreamSessionPacketReq, srv VMService_PullServer) error {
	return status.Errorf(codes.Unimplemented, "method Pull not implemented")
}

func RegisterVMServiceServer(s *grpc.Server, srv VMServiceServer) {
	s.RegisterService(&_VMService_serviceDesc, srv)
}

func _VMService_NotifyStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).NotifyStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.VMService/NotifyStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).NotifyStatus(ctx, req.(*NotifyStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMService_Push_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VMServiceServer).Push(&vMServicePushServer{stream})
}

type VMService_PushServer interface {
	SendAndClose(*StreamSessionPacketRsp) error
	Recv() (*SessionPacket, error)
	grpc.ServerStream
}

type vMServicePushServer struct {
	grpc.ServerStream
}

func (x *vMServicePushServer) SendAndClose(m *StreamSessionPacketRsp) error {
	return x.ServerStream.SendMsg(m)
}

func (x *vMServicePushServer) Recv() (*SessionPacket, error) {
	m := new(SessionPacket)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _VMService_Pull_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamSessionPacketReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VMServiceServer).Pull(m, &vMServicePullServer{stream})
}

type VMService_PullServer interface {
	Send(*SessionPacket) error
	grpc.ServerStream
}

type vMServicePullServer struct {
	grpc.ServerStream
}

func (x *vMServicePullServer) Send(m *SessionPacket) error {
	return x.ServerStream.SendMsg(m)
}

var _VMService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.VMService",
	HandlerType: (*VMServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotifyStatus",
			Handler:    _VMService_NotifyStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Push",
			Handler:       _VMService_Push_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Pull",
			Handler:       _VMService_Pull_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ghost.proto",
}
