// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ghost.proto

package ghost

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GhostPacket struct {
	CmdId                uint32   `protobuf:"varint,1,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"`
	UserData             uint32   `protobuf:"varint,2,opt,name=user_data,json=userData,proto3" json:"user_data,omitempty"`
	Timestamp            uint32   `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Sessions             []uint64 `protobuf:"varint,4,rep,packed,name=sessions,proto3" json:"sessions,omitempty"`
	Body                 string   `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GhostPacket) Reset()         { *m = GhostPacket{} }
func (m *GhostPacket) String() string { return proto.CompactTextString(m) }
func (*GhostPacket) ProtoMessage()    {}
func (*GhostPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_77edc9f77fb63d46, []int{0}
}

func (m *GhostPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GhostPacket.Unmarshal(m, b)
}
func (m *GhostPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GhostPacket.Marshal(b, m, deterministic)
}
func (m *GhostPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GhostPacket.Merge(m, src)
}
func (m *GhostPacket) XXX_Size() int {
	return xxx_messageInfo_GhostPacket.Size(m)
}
func (m *GhostPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_GhostPacket.DiscardUnknown(m)
}

var xxx_messageInfo_GhostPacket proto.InternalMessageInfo

func (m *GhostPacket) GetCmdId() uint32 {
	if m != nil {
		return m.CmdId
	}
	return 0
}

func (m *GhostPacket) GetUserData() uint32 {
	if m != nil {
		return m.UserData
	}
	return 0
}

func (m *GhostPacket) GetTimestamp() uint32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *GhostPacket) GetSessions() []uint64 {
	if m != nil {
		return m.Sessions
	}
	return nil
}

func (m *GhostPacket) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type GhostUserasset struct {
	Uuid                 uint64   `protobuf:"varint,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Version              uint64   `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Asset                string   `protobuf:"bytes,3,opt,name=asset,proto3" json:"asset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GhostUserasset) Reset()         { *m = GhostUserasset{} }
func (m *GhostUserasset) String() string { return proto.CompactTextString(m) }
func (*GhostUserasset) ProtoMessage()    {}
func (*GhostUserasset) Descriptor() ([]byte, []int) {
	return fileDescriptor_77edc9f77fb63d46, []int{1}
}

func (m *GhostUserasset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GhostUserasset.Unmarshal(m, b)
}
func (m *GhostUserasset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GhostUserasset.Marshal(b, m, deterministic)
}
func (m *GhostUserasset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GhostUserasset.Merge(m, src)
}
func (m *GhostUserasset) XXX_Size() int {
	return xxx_messageInfo_GhostUserasset.Size(m)
}
func (m *GhostUserasset) XXX_DiscardUnknown() {
	xxx_messageInfo_GhostUserasset.DiscardUnknown(m)
}

var xxx_messageInfo_GhostUserasset proto.InternalMessageInfo

func (m *GhostUserasset) GetUuid() uint64 {
	if m != nil {
		return m.Uuid
	}
	return 0
}

func (m *GhostUserasset) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *GhostUserasset) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

type RegisterVmReq struct {
	Division             string   `protobuf:"bytes,1,opt,name=division,proto3" json:"division,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterVmReq) Reset()         { *m = RegisterVmReq{} }
func (m *RegisterVmReq) String() string { return proto.CompactTextString(m) }
func (*RegisterVmReq) ProtoMessage()    {}
func (*RegisterVmReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_77edc9f77fb63d46, []int{2}
}

func (m *RegisterVmReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterVmReq.Unmarshal(m, b)
}
func (m *RegisterVmReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterVmReq.Marshal(b, m, deterministic)
}
func (m *RegisterVmReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterVmReq.Merge(m, src)
}
func (m *RegisterVmReq) XXX_Size() int {
	return xxx_messageInfo_RegisterVmReq.Size(m)
}
func (m *RegisterVmReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterVmReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterVmReq proto.InternalMessageInfo

func (m *RegisterVmReq) GetDivision() string {
	if m != nil {
		return m.Division
	}
	return ""
}

type RegisterVmRsp struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterVmRsp) Reset()         { *m = RegisterVmRsp{} }
func (m *RegisterVmRsp) String() string { return proto.CompactTextString(m) }
func (*RegisterVmRsp) ProtoMessage()    {}
func (*RegisterVmRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_77edc9f77fb63d46, []int{3}
}

func (m *RegisterVmRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterVmRsp.Unmarshal(m, b)
}
func (m *RegisterVmRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterVmRsp.Marshal(b, m, deterministic)
}
func (m *RegisterVmRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterVmRsp.Merge(m, src)
}
func (m *RegisterVmRsp) XXX_Size() int {
	return xxx_messageInfo_RegisterVmRsp.Size(m)
}
func (m *RegisterVmRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterVmRsp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterVmRsp proto.InternalMessageInfo

func (m *RegisterVmRsp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *RegisterVmRsp) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type UnregisterVmReq struct {
	Division             string   `protobuf:"bytes,1,opt,name=division,proto3" json:"division,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnregisterVmReq) Reset()         { *m = UnregisterVmReq{} }
func (m *UnregisterVmReq) String() string { return proto.CompactTextString(m) }
func (*UnregisterVmReq) ProtoMessage()    {}
func (*UnregisterVmReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_77edc9f77fb63d46, []int{4}
}

func (m *UnregisterVmReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnregisterVmReq.Unmarshal(m, b)
}
func (m *UnregisterVmReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnregisterVmReq.Marshal(b, m, deterministic)
}
func (m *UnregisterVmReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnregisterVmReq.Merge(m, src)
}
func (m *UnregisterVmReq) XXX_Size() int {
	return xxx_messageInfo_UnregisterVmReq.Size(m)
}
func (m *UnregisterVmReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UnregisterVmReq.DiscardUnknown(m)
}

var xxx_messageInfo_UnregisterVmReq proto.InternalMessageInfo

func (m *UnregisterVmReq) GetDivision() string {
	if m != nil {
		return m.Division
	}
	return ""
}

func (m *UnregisterVmReq) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type UnregisterVmRsp struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnregisterVmRsp) Reset()         { *m = UnregisterVmRsp{} }
func (m *UnregisterVmRsp) String() string { return proto.CompactTextString(m) }
func (*UnregisterVmRsp) ProtoMessage()    {}
func (*UnregisterVmRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_77edc9f77fb63d46, []int{5}
}

func (m *UnregisterVmRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnregisterVmRsp.Unmarshal(m, b)
}
func (m *UnregisterVmRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnregisterVmRsp.Marshal(b, m, deterministic)
}
func (m *UnregisterVmRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnregisterVmRsp.Merge(m, src)
}
func (m *UnregisterVmRsp) XXX_Size() int {
	return xxx_messageInfo_UnregisterVmRsp.Size(m)
}
func (m *UnregisterVmRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_UnregisterVmRsp.DiscardUnknown(m)
}

var xxx_messageInfo_UnregisterVmRsp proto.InternalMessageInfo

func (m *UnregisterVmRsp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *UnregisterVmRsp) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type SendPacketReq struct {
	Packets              []*GhostPacket `protobuf:"bytes,1,rep,name=packets,proto3" json:"packets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SendPacketReq) Reset()         { *m = SendPacketReq{} }
func (m *SendPacketReq) String() string { return proto.CompactTextString(m) }
func (*SendPacketReq) ProtoMessage()    {}
func (*SendPacketReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_77edc9f77fb63d46, []int{6}
}

func (m *SendPacketReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendPacketReq.Unmarshal(m, b)
}
func (m *SendPacketReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendPacketReq.Marshal(b, m, deterministic)
}
func (m *SendPacketReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendPacketReq.Merge(m, src)
}
func (m *SendPacketReq) XXX_Size() int {
	return xxx_messageInfo_SendPacketReq.Size(m)
}
func (m *SendPacketReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendPacketReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendPacketReq proto.InternalMessageInfo

func (m *SendPacketReq) GetPackets() []*GhostPacket {
	if m != nil {
		return m.Packets
	}
	return nil
}

type SendPacketRsp struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendPacketRsp) Reset()         { *m = SendPacketRsp{} }
func (m *SendPacketRsp) String() string { return proto.CompactTextString(m) }
func (*SendPacketRsp) ProtoMessage()    {}
func (*SendPacketRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_77edc9f77fb63d46, []int{7}
}

func (m *SendPacketRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendPacketRsp.Unmarshal(m, b)
}
func (m *SendPacketRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendPacketRsp.Marshal(b, m, deterministic)
}
func (m *SendPacketRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendPacketRsp.Merge(m, src)
}
func (m *SendPacketRsp) XXX_Size() int {
	return xxx_messageInfo_SendPacketRsp.Size(m)
}
func (m *SendPacketRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SendPacketRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SendPacketRsp proto.InternalMessageInfo

func (m *SendPacketRsp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *SendPacketRsp) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type LoadUserassetReq struct {
	Uuids                []uint64 `protobuf:"varint,1,rep,packed,name=uuids,proto3" json:"uuids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadUserassetReq) Reset()         { *m = LoadUserassetReq{} }
func (m *LoadUserassetReq) String() string { return proto.CompactTextString(m) }
func (*LoadUserassetReq) ProtoMessage()    {}
func (*LoadUserassetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_77edc9f77fb63d46, []int{8}
}

func (m *LoadUserassetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadUserassetReq.Unmarshal(m, b)
}
func (m *LoadUserassetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadUserassetReq.Marshal(b, m, deterministic)
}
func (m *LoadUserassetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadUserassetReq.Merge(m, src)
}
func (m *LoadUserassetReq) XXX_Size() int {
	return xxx_messageInfo_LoadUserassetReq.Size(m)
}
func (m *LoadUserassetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadUserassetReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoadUserassetReq proto.InternalMessageInfo

func (m *LoadUserassetReq) GetUuids() []uint64 {
	if m != nil {
		return m.Uuids
	}
	return nil
}

type LoadUserassetRsp struct {
	Result               int32             `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Userassets           []*GhostUserasset `protobuf:"bytes,2,rep,name=userassets,proto3" json:"userassets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *LoadUserassetRsp) Reset()         { *m = LoadUserassetRsp{} }
func (m *LoadUserassetRsp) String() string { return proto.CompactTextString(m) }
func (*LoadUserassetRsp) ProtoMessage()    {}
func (*LoadUserassetRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_77edc9f77fb63d46, []int{9}
}

func (m *LoadUserassetRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadUserassetRsp.Unmarshal(m, b)
}
func (m *LoadUserassetRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadUserassetRsp.Marshal(b, m, deterministic)
}
func (m *LoadUserassetRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadUserassetRsp.Merge(m, src)
}
func (m *LoadUserassetRsp) XXX_Size() int {
	return xxx_messageInfo_LoadUserassetRsp.Size(m)
}
func (m *LoadUserassetRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadUserassetRsp.DiscardUnknown(m)
}

var xxx_messageInfo_LoadUserassetRsp proto.InternalMessageInfo

func (m *LoadUserassetRsp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *LoadUserassetRsp) GetUserassets() []*GhostUserasset {
	if m != nil {
		return m.Userassets
	}
	return nil
}

type SaveUserassetReq struct {
	Userassets           []*GhostUserasset `protobuf:"bytes,1,rep,name=userassets,proto3" json:"userassets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SaveUserassetReq) Reset()         { *m = SaveUserassetReq{} }
func (m *SaveUserassetReq) String() string { return proto.CompactTextString(m) }
func (*SaveUserassetReq) ProtoMessage()    {}
func (*SaveUserassetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_77edc9f77fb63d46, []int{10}
}

func (m *SaveUserassetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveUserassetReq.Unmarshal(m, b)
}
func (m *SaveUserassetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveUserassetReq.Marshal(b, m, deterministic)
}
func (m *SaveUserassetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveUserassetReq.Merge(m, src)
}
func (m *SaveUserassetReq) XXX_Size() int {
	return xxx_messageInfo_SaveUserassetReq.Size(m)
}
func (m *SaveUserassetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveUserassetReq.DiscardUnknown(m)
}

var xxx_messageInfo_SaveUserassetReq proto.InternalMessageInfo

func (m *SaveUserassetReq) GetUserassets() []*GhostUserasset {
	if m != nil {
		return m.Userassets
	}
	return nil
}

type SaveUserassetRsp struct {
	Ok                   []uint64 `protobuf:"varint,1,rep,packed,name=ok,proto3" json:"ok,omitempty"`
	Fail                 []uint64 `protobuf:"varint,2,rep,packed,name=fail,proto3" json:"fail,omitempty"`
	FailErrno            []int32  `protobuf:"varint,3,rep,packed,name=fail_errno,json=failErrno,proto3" json:"fail_errno,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveUserassetRsp) Reset()         { *m = SaveUserassetRsp{} }
func (m *SaveUserassetRsp) String() string { return proto.CompactTextString(m) }
func (*SaveUserassetRsp) ProtoMessage()    {}
func (*SaveUserassetRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_77edc9f77fb63d46, []int{11}
}

func (m *SaveUserassetRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveUserassetRsp.Unmarshal(m, b)
}
func (m *SaveUserassetRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveUserassetRsp.Marshal(b, m, deterministic)
}
func (m *SaveUserassetRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveUserassetRsp.Merge(m, src)
}
func (m *SaveUserassetRsp) XXX_Size() int {
	return xxx_messageInfo_SaveUserassetRsp.Size(m)
}
func (m *SaveUserassetRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveUserassetRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SaveUserassetRsp proto.InternalMessageInfo

func (m *SaveUserassetRsp) GetOk() []uint64 {
	if m != nil {
		return m.Ok
	}
	return nil
}

func (m *SaveUserassetRsp) GetFail() []uint64 {
	if m != nil {
		return m.Fail
	}
	return nil
}

func (m *SaveUserassetRsp) GetFailErrno() []int32 {
	if m != nil {
		return m.FailErrno
	}
	return nil
}

type NotifyStatusReq struct {
	Status               uint32   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyStatusReq) Reset()         { *m = NotifyStatusReq{} }
func (m *NotifyStatusReq) String() string { return proto.CompactTextString(m) }
func (*NotifyStatusReq) ProtoMessage()    {}
func (*NotifyStatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_77edc9f77fb63d46, []int{12}
}

func (m *NotifyStatusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyStatusReq.Unmarshal(m, b)
}
func (m *NotifyStatusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyStatusReq.Marshal(b, m, deterministic)
}
func (m *NotifyStatusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyStatusReq.Merge(m, src)
}
func (m *NotifyStatusReq) XXX_Size() int {
	return xxx_messageInfo_NotifyStatusReq.Size(m)
}
func (m *NotifyStatusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyStatusReq.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyStatusReq proto.InternalMessageInfo

func (m *NotifyStatusReq) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type NotifyStatusRsp struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyStatusRsp) Reset()         { *m = NotifyStatusRsp{} }
func (m *NotifyStatusRsp) String() string { return proto.CompactTextString(m) }
func (*NotifyStatusRsp) ProtoMessage()    {}
func (*NotifyStatusRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_77edc9f77fb63d46, []int{13}
}

func (m *NotifyStatusRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyStatusRsp.Unmarshal(m, b)
}
func (m *NotifyStatusRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyStatusRsp.Marshal(b, m, deterministic)
}
func (m *NotifyStatusRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyStatusRsp.Merge(m, src)
}
func (m *NotifyStatusRsp) XXX_Size() int {
	return xxx_messageInfo_NotifyStatusRsp.Size(m)
}
func (m *NotifyStatusRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyStatusRsp.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyStatusRsp proto.InternalMessageInfo

func (m *NotifyStatusRsp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *NotifyStatusRsp) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type NotifyPacketReq struct {
	Packets              []*GhostPacket `protobuf:"bytes,1,rep,name=packets,proto3" json:"packets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *NotifyPacketReq) Reset()         { *m = NotifyPacketReq{} }
func (m *NotifyPacketReq) String() string { return proto.CompactTextString(m) }
func (*NotifyPacketReq) ProtoMessage()    {}
func (*NotifyPacketReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_77edc9f77fb63d46, []int{14}
}

func (m *NotifyPacketReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyPacketReq.Unmarshal(m, b)
}
func (m *NotifyPacketReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyPacketReq.Marshal(b, m, deterministic)
}
func (m *NotifyPacketReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyPacketReq.Merge(m, src)
}
func (m *NotifyPacketReq) XXX_Size() int {
	return xxx_messageInfo_NotifyPacketReq.Size(m)
}
func (m *NotifyPacketReq) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyPacketReq.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyPacketReq proto.InternalMessageInfo

func (m *NotifyPacketReq) GetPackets() []*GhostPacket {
	if m != nil {
		return m.Packets
	}
	return nil
}

type NotifyPacketRsp struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyPacketRsp) Reset()         { *m = NotifyPacketRsp{} }
func (m *NotifyPacketRsp) String() string { return proto.CompactTextString(m) }
func (*NotifyPacketRsp) ProtoMessage()    {}
func (*NotifyPacketRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_77edc9f77fb63d46, []int{15}
}

func (m *NotifyPacketRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyPacketRsp.Unmarshal(m, b)
}
func (m *NotifyPacketRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyPacketRsp.Marshal(b, m, deterministic)
}
func (m *NotifyPacketRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyPacketRsp.Merge(m, src)
}
func (m *NotifyPacketRsp) XXX_Size() int {
	return xxx_messageInfo_NotifyPacketRsp.Size(m)
}
func (m *NotifyPacketRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyPacketRsp.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyPacketRsp proto.InternalMessageInfo

func (m *NotifyPacketRsp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*GhostPacket)(nil), "ghost.ghost_packet")
	proto.RegisterType((*GhostUserasset)(nil), "ghost.ghost_userasset")
	proto.RegisterType((*RegisterVmReq)(nil), "ghost.register_vm_req")
	proto.RegisterType((*RegisterVmRsp)(nil), "ghost.register_vm_rsp")
	proto.RegisterType((*UnregisterVmReq)(nil), "ghost.unregister_vm_req")
	proto.RegisterType((*UnregisterVmRsp)(nil), "ghost.unregister_vm_rsp")
	proto.RegisterType((*SendPacketReq)(nil), "ghost.send_packet_req")
	proto.RegisterType((*SendPacketRsp)(nil), "ghost.send_packet_rsp")
	proto.RegisterType((*LoadUserassetReq)(nil), "ghost.load_userasset_req")
	proto.RegisterType((*LoadUserassetRsp)(nil), "ghost.load_userasset_rsp")
	proto.RegisterType((*SaveUserassetReq)(nil), "ghost.save_userasset_req")
	proto.RegisterType((*SaveUserassetRsp)(nil), "ghost.save_userasset_rsp")
	proto.RegisterType((*NotifyStatusReq)(nil), "ghost.notify_status_req")
	proto.RegisterType((*NotifyStatusRsp)(nil), "ghost.notify_status_rsp")
	proto.RegisterType((*NotifyPacketReq)(nil), "ghost.notify_packet_req")
	proto.RegisterType((*NotifyPacketRsp)(nil), "ghost.notify_packet_rsp")
}

func init() { proto.RegisterFile("ghost.proto", fileDescriptor_77edc9f77fb63d46) }

var fileDescriptor_77edc9f77fb63d46 = []byte{
	// 607 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0xc5, 0x89, 0x9d, 0xd6, 0xb7, 0x2f, 0x75, 0x28, 0x95, 0x31, 0x20, 0x45, 0x5e, 0x45, 0x54,
	0xed, 0xa2, 0x48, 0xec, 0x28, 0xaf, 0x42, 0x85, 0xd4, 0x02, 0x9a, 0x28, 0x61, 0x69, 0x4d, 0x33,
	0xd3, 0x62, 0x25, 0xb1, 0x8d, 0x67, 0x6c, 0xa9, 0x7f, 0xc1, 0x9e, 0xff, 0xe3, 0x3b, 0xd0, 0x5c,
	0x3f, 0x9a, 0xd8, 0x31, 0x22, 0xac, 0x32, 0xe7, 0xde, 0xe3, 0xe3, 0x33, 0xf7, 0xe1, 0xc0, 0xd6,
	0xed, 0xf7, 0x48, 0xaa, 0x93, 0x38, 0x89, 0x54, 0x44, 0x2c, 0x04, 0xde, 0x4f, 0x03, 0xb6, 0xf1,
	0xe4, 0xc7, 0x6c, 0x32, 0x15, 0x8a, 0x3c, 0x82, 0xde, 0x64, 0xce, 0xfd, 0x80, 0x3b, 0x46, 0xdf,
	0x18, 0xec, 0x50, 0x6b, 0x32, 0xe7, 0x9f, 0x38, 0x79, 0x02, 0x76, 0x2a, 0x45, 0xe2, 0x73, 0xa6,
	0x98, 0xd3, 0xc1, 0xcc, 0xa6, 0x0e, 0x9c, 0x33, 0xc5, 0xc8, 0x53, 0xb0, 0x55, 0x30, 0x17, 0x52,
	0xb1, 0x79, 0xec, 0x74, 0x31, 0x79, 0x1f, 0x20, 0x2e, 0x6c, 0x4a, 0x21, 0x65, 0x10, 0x85, 0xd2,
	0x31, 0xfb, 0xdd, 0x81, 0x49, 0x2b, 0x4c, 0x08, 0x98, 0xd7, 0x11, 0xbf, 0x73, 0xac, 0xbe, 0x31,
	0xb0, 0x29, 0x9e, 0xbd, 0x11, 0xec, 0xe5, 0x8e, 0xb4, 0x3e, 0x93, 0x52, 0x28, 0x4d, 0x4b, 0xd3,
	0xc2, 0x92, 0x49, 0xf1, 0x4c, 0x1c, 0xd8, 0xc8, 0x44, 0xa2, 0x65, 0xd0, 0x8f, 0x49, 0x4b, 0x48,
	0x0e, 0xc0, 0xc2, 0xc7, 0xd0, 0x8a, 0x4d, 0x73, 0xe0, 0x1d, 0xc3, 0x5e, 0x22, 0x6e, 0x03, 0xa9,
	0x44, 0xe2, 0x67, 0x73, 0x3f, 0x11, 0x3f, 0xb4, 0x33, 0x1e, 0x64, 0x01, 0x6a, 0x18, 0xc8, 0xad,
	0xb0, 0xf7, 0xaa, 0x46, 0x97, 0x31, 0x39, 0x84, 0x5e, 0x22, 0x64, 0x3a, 0x53, 0x48, 0xb6, 0x68,
	0x81, 0xb4, 0x3b, 0x2e, 0xe4, 0x04, 0x6d, 0xd8, 0x14, 0xcf, 0xde, 0x7b, 0xd8, 0x4f, 0xc3, 0x35,
	0xde, 0xb7, 0x52, 0xe4, 0x75, 0x43, 0x64, 0x4d, 0x17, 0x6f, 0x60, 0x4f, 0x8a, 0x90, 0x17, 0xbd,
	0x45, 0x0f, 0xc7, 0xb0, 0x91, 0x23, 0xe9, 0x18, 0xfd, 0xee, 0x60, 0xeb, 0xf4, 0xe1, 0x49, 0x3e,
	0x16, 0x8b, 0x53, 0x40, 0x4b, 0x8e, 0x2e, 0xc3, 0x92, 0xc2, 0x9a, 0x06, 0x9e, 0x03, 0x99, 0x45,
	0x8c, 0xdf, 0xb7, 0x12, 0x3d, 0x1c, 0x80, 0xa5, 0x5b, 0x98, 0x3b, 0x30, 0x69, 0x0e, 0x3c, 0xde,
	0xe4, 0xfe, 0xe5, 0x6d, 0x2f, 0x01, 0x2a, 0xa2, 0x74, 0x3a, 0x78, 0x95, 0xc3, 0xa5, 0xab, 0x54,
	0x69, 0xba, 0xc0, 0xf4, 0x2e, 0x81, 0x48, 0x96, 0x89, 0x9a, 0xa3, 0x65, 0x35, 0xe3, 0x9f, 0xd5,
	0xbe, 0x35, 0xd5, 0x64, 0x4c, 0x76, 0xa1, 0x13, 0x4d, 0x8b, 0xcb, 0x75, 0xa2, 0xa9, 0xae, 0xcc,
	0x0d, 0x0b, 0x66, 0xe8, 0xd2, 0xa4, 0x78, 0x26, 0xcf, 0x00, 0xf4, 0xaf, 0x2f, 0x92, 0x24, 0x8c,
	0x9c, 0x6e, 0xbf, 0x3b, 0xb0, 0xa8, 0xad, 0x23, 0x1f, 0x74, 0xc0, 0x3b, 0x82, 0xfd, 0x30, 0x52,
	0xc1, 0xcd, 0x9d, 0x2f, 0x15, 0x53, 0xa9, 0x44, 0x97, 0x87, 0xd0, 0xcb, 0x51, 0xb1, 0x9b, 0x05,
	0xd2, 0x73, 0x52, 0x23, 0xaf, 0xd9, 0xa6, 0x77, 0x95, 0xc0, 0xff, 0x4f, 0xca, 0x51, 0x43, 0xa3,
	0xdd, 0xc4, 0xe9, 0xef, 0x0e, 0x6c, 0x5f, 0x68, 0x99, 0xa1, 0x48, 0xb2, 0x60, 0x22, 0xc8, 0x19,
	0x00, 0x2d, 0x06, 0x7d, 0x7c, 0x45, 0xca, 0xd2, 0xd7, 0x16, 0xc8, 0x5d, 0x19, 0x97, 0xb1, 0xf7,
	0x80, 0x9c, 0xc3, 0xf6, 0xa8, 0x5a, 0x95, 0xf1, 0x15, 0x71, 0x0a, 0x66, 0x63, 0x09, 0xdd, 0x96,
	0x0c, 0xaa, 0x5c, 0xc0, 0xce, 0x65, 0xc4, 0xf8, 0x48, 0x8a, 0xe4, 0x2d, 0x7e, 0x78, 0x1e, 0x17,
	0xe4, 0xe6, 0x10, 0xbb, 0x6d, 0xa9, 0x52, 0x68, 0xc8, 0x32, 0xd1, 0x14, 0x6a, 0xce, 0x9e, 0xdb,
	0x96, 0x42, 0xa1, 0x33, 0x80, 0xa1, 0x08, 0xf9, 0xd7, 0xfc, 0xe3, 0x5c, 0xde, 0xbf, 0xb6, 0xd4,
	0xee, 0xca, 0xb8, 0x7e, 0xfe, 0xf4, 0x97, 0x01, 0xf6, 0xf8, 0xaa, 0xac, 0xf2, 0x47, 0xd8, 0xfd,
	0x12, 0x7e, 0xc6, 0x2e, 0x0d, 0x71, 0x52, 0xaa, 0x3a, 0x35, 0x86, 0xcd, 0x6d, 0xc9, 0xa0, 0xab,
	0x05, 0x9d, 0xc2, 0x59, 0x8d, 0xbd, 0xe0, 0xad, 0x25, 0xa3, 0x75, 0xae, 0x7b, 0xf8, 0x5f, 0xf4,
	0xe2, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe9, 0x66, 0x86, 0x33, 0x9a, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GhostServiceClient is the client API for GhostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GhostServiceClient interface {
	// vm management
	RegisterVM(ctx context.Context, in *RegisterVmReq, opts ...grpc.CallOption) (*RegisterVmRsp, error)
	UnregisterVM(ctx context.Context, in *UnregisterVmReq, opts ...grpc.CallOption) (*UnregisterVmRsp, error)
	// user asset load & save
	LoadUserAsset(ctx context.Context, in *LoadUserassetReq, opts ...grpc.CallOption) (*LoadUserassetRsp, error)
	SaveUserAsset(ctx context.Context, in *SaveUserassetReq, opts ...grpc.CallOption) (*SaveUserassetRsp, error)
	// send packet to client(s)
	SendPacket(ctx context.Context, in *SendPacketReq, opts ...grpc.CallOption) (*SendPacketRsp, error)
}

type ghostServiceClient struct {
	cc *grpc.ClientConn
}

func NewGhostServiceClient(cc *grpc.ClientConn) GhostServiceClient {
	return &ghostServiceClient{cc}
}

func (c *ghostServiceClient) RegisterVM(ctx context.Context, in *RegisterVmReq, opts ...grpc.CallOption) (*RegisterVmRsp, error) {
	out := new(RegisterVmRsp)
	err := c.cc.Invoke(ctx, "/ghost.GhostService/RegisterVM", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ghostServiceClient) UnregisterVM(ctx context.Context, in *UnregisterVmReq, opts ...grpc.CallOption) (*UnregisterVmRsp, error) {
	out := new(UnregisterVmRsp)
	err := c.cc.Invoke(ctx, "/ghost.GhostService/UnregisterVM", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ghostServiceClient) LoadUserAsset(ctx context.Context, in *LoadUserassetReq, opts ...grpc.CallOption) (*LoadUserassetRsp, error) {
	out := new(LoadUserassetRsp)
	err := c.cc.Invoke(ctx, "/ghost.GhostService/LoadUserAsset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ghostServiceClient) SaveUserAsset(ctx context.Context, in *SaveUserassetReq, opts ...grpc.CallOption) (*SaveUserassetRsp, error) {
	out := new(SaveUserassetRsp)
	err := c.cc.Invoke(ctx, "/ghost.GhostService/SaveUserAsset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ghostServiceClient) SendPacket(ctx context.Context, in *SendPacketReq, opts ...grpc.CallOption) (*SendPacketRsp, error) {
	out := new(SendPacketRsp)
	err := c.cc.Invoke(ctx, "/ghost.GhostService/SendPacket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GhostServiceServer is the server API for GhostService service.
type GhostServiceServer interface {
	// vm management
	RegisterVM(context.Context, *RegisterVmReq) (*RegisterVmRsp, error)
	UnregisterVM(context.Context, *UnregisterVmReq) (*UnregisterVmRsp, error)
	// user asset load & save
	LoadUserAsset(context.Context, *LoadUserassetReq) (*LoadUserassetRsp, error)
	SaveUserAsset(context.Context, *SaveUserassetReq) (*SaveUserassetRsp, error)
	// send packet to client(s)
	SendPacket(context.Context, *SendPacketReq) (*SendPacketRsp, error)
}

// UnimplementedGhostServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGhostServiceServer struct {
}

func (*UnimplementedGhostServiceServer) RegisterVM(ctx context.Context, req *RegisterVmReq) (*RegisterVmRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterVM not implemented")
}
func (*UnimplementedGhostServiceServer) UnregisterVM(ctx context.Context, req *UnregisterVmReq) (*UnregisterVmRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterVM not implemented")
}
func (*UnimplementedGhostServiceServer) LoadUserAsset(ctx context.Context, req *LoadUserassetReq) (*LoadUserassetRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadUserAsset not implemented")
}
func (*UnimplementedGhostServiceServer) SaveUserAsset(ctx context.Context, req *SaveUserassetReq) (*SaveUserassetRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveUserAsset not implemented")
}
func (*UnimplementedGhostServiceServer) SendPacket(ctx context.Context, req *SendPacketReq) (*SendPacketRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPacket not implemented")
}

func RegisterGhostServiceServer(s *grpc.Server, srv GhostServiceServer) {
	s.RegisterService(&_GhostService_serviceDesc, srv)
}

func _GhostService_RegisterVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterVmReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GhostServiceServer).RegisterVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ghost.GhostService/RegisterVM",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GhostServiceServer).RegisterVM(ctx, req.(*RegisterVmReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GhostService_UnregisterVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterVmReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GhostServiceServer).UnregisterVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ghost.GhostService/UnregisterVM",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GhostServiceServer).UnregisterVM(ctx, req.(*UnregisterVmReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GhostService_LoadUserAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadUserassetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GhostServiceServer).LoadUserAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ghost.GhostService/LoadUserAsset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GhostServiceServer).LoadUserAsset(ctx, req.(*LoadUserassetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GhostService_SaveUserAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveUserassetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GhostServiceServer).SaveUserAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ghost.GhostService/SaveUserAsset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GhostServiceServer).SaveUserAsset(ctx, req.(*SaveUserassetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GhostService_SendPacket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendPacketReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GhostServiceServer).SendPacket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ghost.GhostService/SendPacket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GhostServiceServer).SendPacket(ctx, req.(*SendPacketReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _GhostService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ghost.GhostService",
	HandlerType: (*GhostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterVM",
			Handler:    _GhostService_RegisterVM_Handler,
		},
		{
			MethodName: "UnregisterVM",
			Handler:    _GhostService_UnregisterVM_Handler,
		},
		{
			MethodName: "LoadUserAsset",
			Handler:    _GhostService_LoadUserAsset_Handler,
		},
		{
			MethodName: "SaveUserAsset",
			Handler:    _GhostService_SaveUserAsset_Handler,
		},
		{
			MethodName: "SendPacket",
			Handler:    _GhostService_SendPacket_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ghost.proto",
}

// VMServiceClient is the client API for VMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VMServiceClient interface {
	OnNotifyStatus(ctx context.Context, in *NotifyStatusReq, opts ...grpc.CallOption) (*NotifyStatusRsp, error)
	OnNotifyPacket(ctx context.Context, in *NotifyPacketReq, opts ...grpc.CallOption) (*NotifyPacketRsp, error)
}

type vMServiceClient struct {
	cc *grpc.ClientConn
}

func NewVMServiceClient(cc *grpc.ClientConn) VMServiceClient {
	return &vMServiceClient{cc}
}

func (c *vMServiceClient) OnNotifyStatus(ctx context.Context, in *NotifyStatusReq, opts ...grpc.CallOption) (*NotifyStatusRsp, error) {
	out := new(NotifyStatusRsp)
	err := c.cc.Invoke(ctx, "/ghost.VMService/OnNotifyStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServiceClient) OnNotifyPacket(ctx context.Context, in *NotifyPacketReq, opts ...grpc.CallOption) (*NotifyPacketRsp, error) {
	out := new(NotifyPacketRsp)
	err := c.cc.Invoke(ctx, "/ghost.VMService/OnNotifyPacket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VMServiceServer is the server API for VMService service.
type VMServiceServer interface {
	OnNotifyStatus(context.Context, *NotifyStatusReq) (*NotifyStatusRsp, error)
	OnNotifyPacket(context.Context, *NotifyPacketReq) (*NotifyPacketRsp, error)
}

// UnimplementedVMServiceServer can be embedded to have forward compatible implementations.
type UnimplementedVMServiceServer struct {
}

func (*UnimplementedVMServiceServer) OnNotifyStatus(ctx context.Context, req *NotifyStatusReq) (*NotifyStatusRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnNotifyStatus not implemented")
}
func (*UnimplementedVMServiceServer) OnNotifyPacket(ctx context.Context, req *NotifyPacketReq) (*NotifyPacketRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnNotifyPacket not implemented")
}

func RegisterVMServiceServer(s *grpc.Server, srv VMServiceServer) {
	s.RegisterService(&_VMService_serviceDesc, srv)
}

func _VMService_OnNotifyStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).OnNotifyStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ghost.VMService/OnNotifyStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).OnNotifyStatus(ctx, req.(*NotifyStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMService_OnNotifyPacket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyPacketReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).OnNotifyPacket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ghost.VMService/OnNotifyPacket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).OnNotifyPacket(ctx, req.(*NotifyPacketReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _VMService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ghost.VMService",
	HandlerType: (*VMServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnNotifyStatus",
			Handler:    _VMService_OnNotifyStatus_Handler,
		},
		{
			MethodName: "OnNotifyPacket",
			Handler:    _VMService_OnNotifyPacket_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ghost.proto",
}
